### ISSUE TITLE
彩色图转灰度图的时候可以使用decolor

### ISSUE THREAD

**Issue by DelightRun** [liuruoze/EasyPR#101]
传统的彩色图转灰度图算法对对比度不高的图片效果不好，因此OpenCV3中引入了个新方法叫decolor，建议使用此方法替换cvtColor。

文档：http://docs.opencv.org/3.0-beta/modules/photo/doc/decolor.html
论文：Cewu Lu, Li Xu, Jiaya Jia, “Contrast Preserving Decolorization”, IEEE International Conference on Computational Photography (ICCP), 2012.

**Comment by liuruoze** [comment]
谢谢建议，如果能够附上实际测试的效果就最好了。
这样可以非常清楚地看到这种对比度增强对于车牌识别的提升力度。

**Comment by DelightRun** [comment]
但是他那个函数有个bug，有的图片出来结果全是0，有空的话得分析下源码
