### ISSUE TITLE
编译出错lnk 1104

### ISSUE THREAD

**Issue by jssunie** [liuruoze/EasyPR#102]
我是opencv3.1+ vs2015
配置正确，其他的一些demo程序也能正常运行，但是编译easyPR的时候，提醒lnk1104，无法打开文件 opencv_world300d.dll
![default](https://cloud.githubusercontent.com/assets/14073112/14768123/93a935e4-0a6b-11e6-97b7-bc15384ec9c3.JPG)

**Comment by liuruoze** [comment]
默认配置文件是opencv3.0的，如果用3.1的，需要手动修改下，建议google下相关配置文件修改的方法。

**Comment by jssunie** [comment]
@liuruoze 将demo的链接器的附加依赖项改为opencv_world310d.lib后解决问题，我之前没有注意这个。
