### ISSUE TITLE
在windows 10运行报错

### ISSUE THREAD

**Issue by kuangyunsheng** [liuruoze/EasyPR#107]
我的机器上只有windows10和ubuntun。在ubuntu下，程序可以正常运行，但Windows10确报错。

![image](https://cloud.githubusercontent.com/assets/10006626/15802997/b3289cc0-2afa-11e6-84c3-9a80140ecef1.png)

![image](https://cloud.githubusercontent.com/assets/10006626/15802986/2be6c264-2afa-11e6-95ca-7bae7c8ca08e.png)

**Comment by liuruoze** [comment]
首先检查下自己的PATH环境变量是否有针对其他版本vs的DLL，如果有就删除。如果没有，设置项目运行库为多线程调试DLL（/MDd）再试试。
