### ISSUE TITLE
EasyPR 1.4 linux版本，编译时很多语法错误，请帮助！

### ISSUE THREAD

**Issue by ghpass** [liuruoze/EasyPR#112]
运行环境：
--centos6
--GCC4.8.5
--opencv3.1.0
运行./build.sh后报一堆错误
/data/EasyPR-1.4/include/easypr/util/util.h:76: error: expected initializer before ‘:’ token
/data/EasyPR-1.4/include/easypr/util/util.h:79: error: expected primary-expression before ‘}’ token
/data/EasyPR-1.4/include/easypr/util/util.h:79: error: expected ‘;’ before ‘}’ token
/data/EasyPR-1.4/include/easypr/util/util.h:79: error: expected primary-expression before ‘}’ token
/data/EasyPR-1.4/include/easypr/util/util.h:79: error: expected ‘)’ before ‘}’ token
/data/EasyPR-1.4/include/easypr/util/util.h:79: error: expected primary-expression before ‘}’ token
/data/EasyPR-1.4/include/easypr/util/util.h:79: error: expected ‘;’ before ‘}’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp: In member function ‘int easypr::CCharsRecognise::charsRecognise(cv::Mat, std::string&)’:
/data/EasyPR-1.4/src/core/chars_recognise.cpp:15: error: expected initializer before ‘:’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp:19: error: expected primary-expression before ‘}’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp:19: error: expected ‘;’ before ‘}’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp:19: error: expected primary-expression before ‘}’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp:19: error: expected ‘)’ before ‘}’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp:19: error: expected primary-expression before ‘}’ token
/data/EasyPR-1.4/src/core/chars_recognise.cpp:19: error: expected ‘;’ before ‘}’ token
[ 25%] Building CXX object CMakeFiles/easypr.dir/src/core/plate.cpp.o
make[2]: **\* [CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: **\* [CMakeFiles/easypr.dir/src/core/chars_recognise.cpp.o] Error 1
/data/EasyPR-1.4/src/core/chars_segment.cpp: In member function ‘int easypr::CCharsSegment::charsSegment(cv::Mat, std::vector<cv::Mat, std::allocator<cv::Mat> >&)’:
/data/EasyPR-1.4/src/core/chars_segment.cpp:174: error: expected primary-expression before ‘[’ token
/data/EasyPR-1.4/src/core/chars_segment.cpp:174: error: expected primary-expression before ‘]’ token
/data/EasyPR-1.4/src/core/chars_segment.cpp:174: error: expected primary-expression before ‘const’
/data/EasyPR-1.4/src/core/chars_segment.cpp:174: error: expected primary-expression before ‘const’
make[2]: **\* [CMakeFiles/easypr.dir/src/core/chars_segment.cpp.o] Error 1
make[1]: **\* [CMakeFiles/easypr.dir/all] Error 2

**Comment by ghpass** [comment]
强制设置-c++11解决此问题。

**Comment by RobotJiang** [comment]
@ghpass 请问，如何强制设置？

**Comment by ghpass** [comment]
CMakelists.txt里注释掉如下内容：
#if(COMPILER_SUPPORTS_CXX11)
#    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
#elseif(COMPILER_SUPPORTS_CXX0X)
#    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
#else()
#    message(STATUS "The compiler ${CMAKE_CXX_COMPILER} doesn’t support C++11. Please upgrade or use a different C++compiler.")
#endif()
然后增加：
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

当然，GCC必须是4.8.*，我用的是4.8,5。
还遇到小问题，/usr/bin与/usr/local/bin下的gcc、cc、c++、g++版本不一样，安装gcc缺省部署到/usr/local/bin下。但EasyPR到/usr/.bin下找编译器，所以要加软链接（ln  -s）。

**Comment by ghpass** [comment]
CMakelists.txt里注释掉如下内容：
 #if(COMPILER_SUPPORTS_CXX11)
      # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
#elseif(COMPILER_SUPPORTS_CXX0X)
     #set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
#else()
     #message(STATUS "The compiler ${CMAKE_CXX_COMPILER} doesn’t support C++11. Please upgrade or use a different C++compiler.")
#endif()
 然后增加：
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

当然，GCC必须是4.8.*，我用的是4.8,5。
 还遇到小问题，/usr/bin与/usr/local/bin下的gcc、cc、c++、g++版本不一样，安装gcc缺省部署到/usr/local/bin下。但EasyPR到/usr/.bin下找编译器，所以要加软链接（ln -s）。
