### ISSUE TITLE
Mac 上build报错

### ISSUE THREAD

**Issue by RobotJiang** [liuruoze/EasyPR#115]
error: non-const lvalue reference to type 'cv::Mat' cannot bind to a temporary of
      type 'cv::Mat'

有人遇见过没有？如何解决？

**Comment by micooz** [comment]
这个是很早之前的问题，请下载最近的1.3或者1.4版本：

* [v1.3](https://github.com/liuruoze/EasyPR/releases/tag/v1.3)
* [v1.4](https://github.com/liuruoze/EasyPR/releases/tag/v1.4)
