### ISSUE TITLE
SVM预测异常

### ISSUE THREAD

**Issue by liuruoze** [liuruoze/EasyPR#119]
Opencv 3.0的可能问题，虽然1.5版能够训练成功，但用训练好的文件去预测时，效果比原先的有大幅度下降。
目前推测问题可能原因在3.0的svm的写入文件函数：
![svm](https://cloud.githubusercontent.com/assets/8255297/16604406/71b1006e-4357-11e6-9fd5-4c47ce29bb7f.jpg)
可以看到，直接训练后模型预测结果跟2.x一致。但是写入文件以后，文件内容跟2.x的差异很大，导致在预测时也会有问题。例如raw output形式跟2.x差异很大。2.x预测为正的文件的rawoutput值为负，而3.0值都是正的，非常奇怪。

**Comment by xmycll** [comment]
我也遇到了这样的问题，怎么解决啊

**Comment by xmycll** [comment]
找到什么问题了

**Comment by boarbing** [comment]
@xmycll 你找到什么问题了吗？可否分享一下？

**Comment by cyf520** [comment]
同求解决办法

**Comment by cyf520** [comment]
@boarbing 请问你解决问题了吗？

**Comment by boarbing** [comment]
@cyf520 我也没找到解决的办法。

**Comment by cyf520** [comment]
@boarbing 好的，谢谢~

**Comment by tka** [comment]
應該是撞到 https://github.com/opencv/opencv/issues/5054 SVM write/load problems with kernels other than linear 這個問題

opencv 已經在 https://github.com/opencv/opencv/pull/6345 修掉了

**Comment by liuruoze** [comment]
Wonderful！This has greatly solved this problem. 
![default](https://cloud.githubusercontent.com/assets/8255297/21469593/38440306-ca95-11e6-93e5-51dd784637ed.PNG)
