### ISSUE TITLE
不能在linux平台上编译

### ISSUE THREAD

**Issue by FuGangqiang** [liuruoze/EasyPR#12]
1. src/include/features.h 与 linux 系统中 features.h 加载顺序有问题
2. 许多源码文件中包含linux中没有的头文件objbase.h, windows.h, io.h
3. src/train/ann_train.cpp 中 GetTickCount 函数未声明
4. src/util/util.cpp 也不能编译成功
5. 源文件编码建议改为 utf-8 类型

**Comment by liuruoze** [comment]
确实有这些问题...
