### ISSUE TITLE
android 版本编译中执行cleanNative命令的时候提示缺少文件

### ISSUE THREAD

**Issue by 369905581** [liuruoze/EasyPR#122]
clean出现 
 What went wrong:
Execution failed for task ':app:cleanNative'.

> A problem occurred starting process 'command 'D:\AndroidSDK\ndk-bundle/ndk-build''
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  然后命令行执行:gradle cleanNative -stacktrace出现下面情况： 
  at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcess
  Launcher.java:25)
      ... 5 more
  Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。

**Comment by liuruoze** [comment]
android的问题去android那个项目主页发会更好一点。
