### ISSUE TITLE
测试ann时crash问题

### ISSUE THREAD

**Issue by sxhebing** [liuruoze/EasyPR#124]
我在虚拟机上测试时发现默认的ann训练支持中文（type为1），稍微修改后测试所有字符训练时发现测试训练结果（ann.xml后）时会crash：
跟踪日志发现是如下代码段：
std::pair<std::string, std::string> AnnTrain::identify(cv::Mat input) {
  cv::Mat feature = charFeatures2(input, kPredictSize);
  float maxVal = -2;
  int result = -1;

  cv::Mat output(1, kCharsTotalNumber, CV_32FC1);
  ann_->predict(feature, output);

  for (int j = 0; j < kCharsTotalNumber; j++) {
    float val = output.at<float>(j);
    // std::cout << "j:" << j << "val:" << val << std::endl;
    if (val > maxVal) {
      maxVal = val;
      result = j;
    }
  }

  auto index = result;
  if (index < kCharactersNumber) {
    return std::make_pair(kChars[index], kChars[index]);
  }
  else {
    const char* key = kChars[index];
    std::string s = key;
    std::string province = kv_->get(s);
    return std::make_pair(s, province);
  }
}

原因是ann_->predict(feature, output)后result的值可能为-1导致，修改方式比较简单，如果result小于0直接返回-1的集合，不过这样就会出现如下的测试结果：
>> Testing characters zh_min in resources/train/ann/zh_min 
>>   [sum: 350, correct: 344, rate: 0.98]
>>   [
       debug_specMat1028: 桂,
       15_18_28: -1,
       15_72_85: -1,
       15_112_150: -1,
       15_116_139: -1,
       15_239_183: 琼
       ...
     ]

测试环境：
GentOs +gcc 4.8.2 + cmake 3.1.3 + 1.5beat + opencv3.1.0

**Comment by sxhebing** [comment]
重新读了些代码，这个版本的中文和其它字符的特征值取值是不一样的，默认都是采用1x120（10+10+100），估计这是导致中文识别为-1的原因

**Comment by zhongxig** [comment]
现在 训练 ann_chinese 失败，这部分代码 什么时候 修复呢？
