### ISSUE TITLE
LNK2001	无法解析的外部符号 public: static char __cdecl XMLNode::setGlobalOptions

### ISSUE THREAD

**Issue by sail-sail** [liuruoze/EasyPR#128]
错误  LNK2001 无法解析的外部符号 "public: static char __cdecl XMLNode::setGlobalOptions(enum XMLNode::XMLCharEncoding,char,char,char)" (?setGlobalOptions@XMLNode@@SADW4XMLCharEncoding@1@DDD@Z) test    E:\EasyPR\test\test.obj 1

**Comment by zomco** [comment]
vs2015? 请试试方法二

**Comment by lizzyYL** [comment]
我也遇到这个问题了 请问你后来怎么解决的？谢谢~

**Comment by liuruoze** [comment]
应该是xmlnode位置没有找到？
