### ISSUE TITLE
局部空间的大津阈值算法

### ISSUE THREAD

**Issue by xiaomaxiao** [liuruoze/EasyPR#129]
介绍中提到的 局部空间的大津阈值算法  有介绍链接么

**Comment by liuruoze** [comment]
可以看博客里的介绍

**Comment by xiaomaxiao** [comment]
@liuruoze  博客里只提到说用了 大津阈值算法 没有讲具体的内容和引子额

**Comment by liuruoze** [comment]
可以看代码，其实非常简单的，就是把图像分成若干grid进行大津阈值。

**Comment by xiaomaxiao** [comment]
@liuruoze  谢谢 已在此处 找到 src/core/core_func.cpp
