### ISSUE TITLE
关于这个工程的作用

### ISSUE THREAD

**Issue by hjm1990818** [liuruoze/EasyPR#131]
师兄，您好，我看工程里有Demo和libeasypr两个工程，您能大概跟我说一下这两个工程的作用吗？第二个libeasypr工程里我没看到main函数呢

**Comment by liuruoze** [comment]
libeasypr是生成静态库的，Demo是调用它，给你示范easypr的作用的。所以在libeasypr里没有main函数。实际使用时，要自己写程序来调用libeasypr这个库。调用方式参考Demo里的代码。
