### ISSUE TITLE
svm训练的图片问题

### ISSUE THREAD

**Issue by yixiu00001** [liuruoze/EasyPR#132]
请问作者svm训练用的是车牌图片，那原始的整幅图片可以share吗？

**Comment by liuruoze** [comment]
很遗憾，原始图片是有版权的。
EasyPR不同于其他开源项目，提供了训练图片，是考虑到中国这里获取这些数据的渠道比较困难，不像国外有完善的协议与贡献者。在中国，数据更多的处于一种保护地位，初学者想要学习机器学习可能会苦于没有数据。因此才开源了这些训练的车牌图片。目前来看，这是已经能做到的最大地步。提供给我数据的人跟我约定过，须对其的原始图片进行保密。因此EasyPR目前只能提供训练图片，不能提供原始的图片share。如果想要测试车牌定位效果，可以看general_test下的图片，这些图片可以在遵循gdst的基础上进行研究，学习与非商业性质的分享。

**Comment by yixiu00001** [comment]
好的，了解了。
图片版权确实是个大问题，谢谢解答。
