### ISSUE TITLE
”不能识别两行的车牌“的问题什么时候支持呢~

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [liuruoze/EasyPR#133]
之前有人问过的，就是，有的车的车牌是由两行组成的，这个时候不能识别出来。这个问题会在什么时候加入easypr之中呢？
之前的问题如下：
https://github.com/liuruoze/EasyPR/issues/85

**Comment by liuruoze** [comment]
现在目前只有一个计划，暂时没有日程的安排。
