### ISSUE TITLE
error C1083: 无法打开包括文件: “thirdparty/mser/mser2.hpp”

### ISSUE THREAD

**Issue by chenyuqiuwan** [liuruoze/EasyPR#135]
thirdparty文件夹下面的四个文件打不开包括：
“thirdparty/textDetect/erfilter.hpp”
“thirdparty/mser/mser2.hpp”: 
“thirdparty/LBP/lbp.hpp”:
“thirdparty/textDetect/erfilter.hpp”
期待您的回复

**Comment by Nocannobb** [comment]
我也遇到了同样的问题，在解决方案资源管理器中thirdparty文件夹是空的，不知到为什么

**Comment by lxgyChen** [comment]
改为../thirdparty

**Comment by insight2620** [comment]
> 改为../thirdparty

谢谢，成功了
