### ISSUE TITLE
SVM打标签时如果图片中车牌不完整算是has还是no

### ISSUE THREAD

**Issue by tju-znn** [liuruoze/EasyPR#137]
有些车牌的省份没有，有些车牌末尾的数字或字母只显示了一半，还有一些车牌倾斜角度很大，上述这先图片中算是有车牌还是没有车牌

**Comment by liuruoze** [comment]
这个也算是计算机视觉中一个未解的难题之一了，这个一般是按照经验法则。根据我的实践，我建议最好不要把这些数据放到训练数据中，也就是说它们既不算has也不算no。
