### ISSUE TITLE
我用1.3版测试SVM训练，训练了17个小时，依然没有完结迹象，这算正常么，到底需要多久，训练用图片是自带learn文件夹中的

### ISSUE THREAD

**Issue by lisx0001** [liuruoze/EasyPR#142]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **System:** CentOS
- **Compiler version/IDE:** gcc4.8
- **CMake version:** 3.5.1
- **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by caozhiyong** [comment]
我也是用的1.3，4分钟左右

**Comment by liuruoze** [comment]
很明显是不正常的，检查一下训练的代码与数据
