### ISSUE TITLE
我用当前1.5版做ANN训练，耗时不长，拿到ANN模型文件之后做车牌识别，程序直接崩溃是怎么回事;ann.xml和ann_chinese.xml需要同步更新么，我只训练出了ann.xml,找不到ann_chinese.xml的生成模块啊，是不是用新训练的ann.xml和旧版的ann_chinese.xml一起用导致的程序崩溃啊

### ISSUE THREAD

**Issue by lisx0001** [liuruoze/EasyPR#143]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **System:** CentOS
- **Compiler version/IDE:** gcc4.8
- **CMake version:** 3.5.1
- **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by liuruoze** [comment]
确实需要同步更新，在ann_train.cpp里
`AnnTrain::AnnTrain(const char* chars_folder, const char* xml)
    : chars_folder_(chars_folder), ann_xml_(xml) {
  ann_ = cv::ml::ANN_MLP::create();
  type = 1;
  kv_ = std::shared_ptr<Kv>(new Kv);
  kv_->load("etc/province_mapping");
}`
改变type的值就会改变生成的ann类型，0是字符，1是中文
