### ISSUE TITLE
Opencv版本选定问题

### ISSUE THREAD

**Issue by attendfov** [liuruoze/EasyPR#147]
hi，请教一个比较入门的问题，这两天在配置EasyPR用于生成libeasypr，发现尝试了很多个Opencv版本都不成功，每个版本都出现各种问题，甚是着急，有的版本是是头文件不包含，有的是SVM或者ANN的成员函数不存在，到目前还没有配置成功过。自己新建Opencv项目编写代码都是OK的。我这边是Windows10系统，IDE是VS2013。望大侠能指导！感谢！

**Comment by liuruoze** [comment]
试试opencv3.0或者懒人版？懒人版地址在readme里就有介绍。
