### ISSUE TITLE
将软件代码用java改写并发布需要添加什么信息

### ISSUE THREAD

**Issue by fan-wenjie** [liuruoze/EasyPR#15]
我将EasyPR的代码改写为Java并发布在github上，请问需要添加什么信息？
项目网址如下：
https://github.com/fan-wenjie/EasyPR-Java

**Comment by liuruoze** [comment]
在readme里说明EasyPR原地址即可，java代码已经通过测试了么？

**Comment by liuruoze** [comment]
已将java版本信息添加到EasyPR的readme里了。

**Comment by fan-wenjie** [comment]
可否留下开发者交流的QQ群或其他交流方式，我最近在研究SVM-2K，可否加入开发者？

**Comment by liuruoze** [comment]
SVM-2K 是SVM的一个改良么？ QQ群 366392603，加时注明"easypr-java版开发者"

**Comment by fan-wenjie** [comment]
SVM2k是SVM的一种改良，我已入群

**Comment by liuruoze** [comment]
由于公司限制原因，我上班时间不在QQ群里，你可以先跟群里的人聊聊
