### ISSUE TITLE
linux make 的时候最终*** 没有规则可以创建“easypr_test”需要的目标“/usr/local/lib/libopencv_videostab.so.3.0.0”。 停止。但是不是要求opencv2.4.8以上就可以了吗？在Windows下vs2013,opencv2.4.9最后运行的时候出现unable to start program '\EasyPR\\bin\debug\libeastpr.lib'

### ISSUE THREAD

**Issue by shendaizi** [liuruoze/EasyPR#151]
linux make 的时候最终*** 没有规则可以创建“easypr_test”需要的目标“/usr/local/lib/libopencv_videostab.so.3.0.0”。 停止。但是不是要求opencv2.4.8以上就可以了吗？在Windows下vs2013,opencv2.4.9最后运行的时候出现unable to start program '\EasyPR\\bin\debug\libeastpr.lib'请问有没有人有同样的错误

**Comment by liuruoze** [comment]
1.3以上的版本都需要opencv3.0以上的版本，如果想用opencv2.4，可以下载1.1或1.2版本
