### ISSUE TITLE
opencv3.2 编译报错解决

### ISSUE THREAD

**Issue by jjz** [liuruoze/EasyPR#152]
**expected '(' for function-style cast or type construction.**  (check one with "chars_identify.cpp")

```
[ 25%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o
.../c/EasyPR/src/core/chars_identify.cpp:20:41: error: expected '(' for function-style cast or type construction
    ann_ = ml::ANN_MLP::load<ml::ANN_MLP>(kDefaultAnnPath);
                             ~~~~~~~~~~~^
.../c/EasyPR/src/core/chars_identify.cpp:21:48: error: expected '(' for function-style cast or type construction
    annChinese_ = ml::ANN_MLP::load<ml::ANN_MLP>(kChineseAnnPath);
                                    ~~~~~~~~~~~^
.../c/EasyPR/src/core/chars_identify.cpp:32:43: error: expected '(' for function-style cast or type construction
      ann_ = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                               ~~~~~~~~~~~^
.../c/EasyPR/src/core/chars_identify.cpp:42:50: error: expected '(' for function-style cast or type construction
      annChinese_ = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                      ~~~~~~~~~~~^
4 errors generated.
make[2]: *** [CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o] Error 1
make[1]: *** [CMakeFiles/easypr.dir/all] Error 2
make: *** [all] Error 2
```

**Please tell us about your environment:**

* **System:** Macos

* **Compiler version/IDE:** gcc4.2.1

* **CMake version:** 3.7.1

* **OpenCV version:** 3.1

**Comment by czy** [comment]
遇到同样错误

**Comment by czy** [comment]
chars_identify.cpp

**Comment by czy** [comment]
编译通过了，做了如下修改：
chars_identify.cpp
load去掉\<ml::ANN_MLP>
plate_judge.cpp
load去掉\<ml::SVM>
svm_train.cpp
load去掉\<cv::ml::SVM>

- System: macOS 10.12.1
- Compiler version/IDE: Apple LLVM version 8.0.0
- CMake version: 3.7.1
- OpenCV version: 3.1

**Comment by jason0539** [comment]
赞

**Comment by rocLv** [comment]
确实有效，赞！

**Comment by liuruoze** [comment]
已修改标题，帮助更多人看到后得知解决方案。

**Comment by 498143049** [comment]
自己不太懂这个，但是 为什么 这样改就是可以的呢？

**Comment by B-one** [comment]
错误	143	error LNK2038: 检测到“RuntimeLibrary”的不匹配项:  值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(main.obj 中)	E:\OpenCV\EasyPR-master\vcprojs\libeasypr.lib(plate_detect.obj)	demo

**Comment by B-one** [comment]
环境为vs2013,openCV3.2,在进行release编译时出现这种情况，debug编译已经通过。

**Comment by liuruoze** [comment]
release版对应的opencv的库需要调整的

**Comment by itriphaxer** [comment]
error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”

在工程上右键-》属性-》c/c++-》代码生成-》运行库
改成（release为MD，debug为MDd）即可解决

**Comment by ZhangXinNan** [comment]
/include/easypr/config.h

-#define CV_VERSION_THREE_ZERO
+// #define CV_VERSION_THREE_ZERO
+#define CV_VERSION_THREE_TWO

**Comment by iamblue** [comment]
@ZhangXinNan thank you ! fixed it!

**Comment by Lucas-Yang** [comment]
@ZhangXinNan +1 fixed it

**Comment by lzufalcon** [comment]
通过自动判断OpenCV版本号彻底解决该问题：https://github.com/liuruoze/EasyPR/pull/286
