### ISSUE TITLE
关于字符识别之前为什么要拉成正方形？

### ISSUE THREAD

**Issue by 7oud** [liuruoze/EasyPR#155]
您好，
        读完你的代码之后，有一个地方不是很明白，为什么字符识别之前要把字符调整为正方形？是因为对识别有帮助么？还是因为相较于长方形，丰富了一些信息？还有就是，为什么要使用二值图像作为特征呢？这样是否是丢失了一些有效信息呢？请指教。

**Comment by liuruoze** [comment]
其实，调整为方形不是一定的步骤。但是很多前人的工作都是调整为方形的，所以这里也只是按照一般做法。另外，二值图像也不是一定的，你可以试试用灰度图像。这里用二值图像是因为我所参照的前人的工作是用到二值图像，有不少模型用的是灰度图像。

**Comment by 7oud** [comment]
谢谢你的答复，希望EasyPR可以做的更好，处理更多更复杂的场景。还有最近新发布的新能源车牌，不知道EasyPR会不会进行针对性的功能丰富呢，期待你的更新。

**Comment by liuruoze** [comment]
谢谢支持，感谢！
