### ISSUE TITLE
Do you have plan to support New Energy Plate?

### ISSUE THREAD

**Issue by xinlinux** [liuruoze/EasyPR#157]
I just upload a picture with  New Energy Plate  in the file attached.
![1282388076](https://cloud.githubusercontent.com/assets/24785520/21490083/b06dc3ca-cc2b-11e6-9f90-2180f3e5d9a3.jpg)

**Comment by liuruoze** [comment]
8个字符........ 残念，几乎可以推翻目前EasyPR里的好几个模块的实现假设了。目前看来，就算解决这些问题，没有足够数量的图片，也无法训练。
而且，现在还有白牌车，黑牌车等车型没有考虑，从优先级来说看来还要等一阵子。
