### ISSUE TITLE
Mac上，识别函数一直不返回结果，并且100%CPU使用率

### ISSUE THREAD

**Issue by 188080501** [liuruoze/EasyPR#158]
macOS 10.11.6
AMD卡
OpenCV3.1

代码就是示例的：
```
    easypr::CPlateRecognize pr;
    pr.setResultShow(false);
    pr.setDetectType(easypr::PR_DETECT_CMSER);

    vector<easypr::CPlate> plateVec;
    Mat src = imread( "/Users/Jason/Desktop/test.jpg" );

    int result = pr.plateRecognize(src, plateVec);
```

pr.plateRecognize一直不返回，CPU100%，内存不发生明显变化
我尝试过一些图片，从35kb，到3MB，均等待2分钟时间，但是都等不到函数返回。

**Comment by 188080501** [comment]
如果需要我这里其他环境信息，请留言，我会去找的

**Comment by PL23K** [comment]
我在linux也是  pr.plateRecognize(src, plateVec);  和 plate.plateLocate(src, results);都是不会返回的，一直阻塞在这里。静态库都不知道怎么进去调试。

**Comment by PL23K** [comment]
你的问题解决了吗？

**Comment by 188080501** [comment]
没有解决。你的CPU使用率也是占满一个核的？

**Comment by rayanywhere** [comment]
你看看是不是那个etc/province_map文件读不到？读文件那边逻辑需要更正下，否则文件不存在的时候就死循环。

**Comment by liuruoze** [comment]
这边确实是一个bug，之后我们会修正它。
