### ISSUE TITLE
v1.2 centos 编译出错

### ISSUE THREAD

**Issue by abanger** [liuruoze/EasyPR#16]
v1.2 centos 编译出错
环境：
2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
opencv-2.4.9

[root@v01lab EasyPR-1.2]# make
Scanning dependencies of target EasyPR
[  5%] Building CXX object CMakeFiles/EasyPR.dir/src/main.cpp.o
In file included from /usr/local/include/opencv2/core/types_c.h:55,
                 from /usr/local/include/opencv2/core/core.hpp:49,
                 from /usr/local/include/opencv2/imgproc/imgproc.hpp:50,
                 from /home/pr/EasyPR-1.2/src/include/prep.h:5,
                 from /home/pr/EasyPR-1.2/src/include/plate_recognize.h:15,
                 from /home/pr/EasyPR-1.2/src/main.cpp:1:
/usr/include/assert.h:39:42: error: missing binary operator before token "("
/usr/include/assert.h:105:42: error: missing binary operator before token "("
In file included from /usr/local/include/opencv2/core/types_c.h:57,
                 from /usr/local/include/opencv2/core/core.hpp:49,
                 from /usr/local/include/opencv2/imgproc/imgproc.hpp:50,
                 from /home/pr/EasyPR-1.2/src/include/prep.h:5,
                 from /home/pr/EasyPR-1.2/src/include/plate_recognize.h:15,
                 from /home/pr/EasyPR-1.2/src/main.cpp:1:
/usr/include/string.h:37:42: error: missing binary operator before token "("
In file included from /usr/include/math.h:34,
                 from /usr/local/include/opencv2/core/types_c.h:94,
                 from /usr/local/include/opencv2/core/core.hpp:49,
                 from /usr/local/include/opencv2/imgproc/imgproc.hpp:50,
                 from /home/pr/EasyPR-1.2/src/include/prep.h:5,
                 from /home/pr/EasyPR-1.2/src/include/plate_recognize.h:15,
                 from /home/pr/EasyPR-1.2/src/main.cpp:1:
/usr/include/bits/huge_val.h:28:18: error: missing binary operator before token "("
/usr/include/bits/huge_val.h:30:20: error: missing binary operator before token "("
....

**Comment by liuruoze** [comment]
我会把它转发给linux版的开发人员，他不一定有时间。在他解决之前请帮忙看看能不能解决，可以的话就直接提交pull request，感谢！

**Comment by Micooz** [comment]
却有这个问题，我正在努力解决它！

**Comment by FuGangqiang** [comment]
可以看看这个提交：
https://github.com/liuruoze/EasyPR/pull/17

**Comment by Micooz** [comment]
@FuGangqiang 不用修改文件名，只需要删除CMakeList.txt中的include_directories即可。
