### ISSUE TITLE
训练ANN时异常

### ISSUE THREAD

**Issue by pimengting** [liuruoze/EasyPR#161]
训练SVM和ANN都发生异常
![image](https://cloud.githubusercontent.com/assets/16531147/21838874/93d9d79a-d80f-11e6-9c0e-6abe888f79a2.png)
如图，char_size部分为0
![image](https://cloud.githubusercontent.com/assets/16531147/21838907/bc23eefc-d80f-11e6-80c7-fb0ac1b93d61.png)

System: windows7

Compiler version/IDE: vs2013

OpenCV version: [ 3.1 ]

**Comment by pimengting** [comment]
已经解决，感谢博主分享

**Comment by xiewu6555** [comment]
请问怎么解决的？能分享一下吗

**Comment by hehainan8605** [comment]
是不是没有解压那个ann.7z和svm.7z?而且要在选择函数中设置文件所在目录和模型名称
![image](https://cloud.githubusercontent.com/assets/16314509/23094154/8b6300ae-f62e-11e6-8b4b-c32eca116800.png)

**Comment by xiewu6555** [comment]
非常感谢你的回答，已解决，谢谢！

2017-02-18 23:04 GMT+08:00 hehainan8605 <notifications@github.com>:
