### ISSUE TITLE
找不到plate.h文件

### ISSUE THREAD

**Issue by cea5** [liuruoze/EasyPR#172]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x ] help wanted
[ ] feature request
```

**Current behavior**
src里的plate.cpp需要#include "easypr\core\plate.h"，但是easypr\core\目录下只有plate.hpp
请问如何解决？

**Please tell us about your environment:**

* **System:** win7

* **Compiler version/IDE:** vs2015

* **CMake version:** 3.5.1

* **OpenCV version:** [ 3.1 ]

**Comment by liuruoze** [comment]
修改任意两者之一使其兼容即可。这是原先代码调整产生的遗留问题。
