### ISSUE TITLE
编译成功后，运行demo.exe控制台卡住不动

### ISSUE THREAD

**Issue by B-one** [liuruoze/EasyPR#174]
**I'm submitting a ...**  (check one with "x")
编译完成后，双击demo.exe没有出现任何信息，卡住不动。同时无法键入任何信息。

**Current behavior**

**Expected/desired behavior**
应该是要像debug版本一样，跳出一个可键入命令的命令行吧，同时还有一些提示文本吧？这个release出来一片黑。。

* **System:** win7

* **Compiler version/IDE:** vs2013

* **CMake version:** 无

* **OpenCV version:** 3.2.0

**Comment by geff86** [comment]
have you solved this problem?
同样的的配置，遇到了同样的问题。release版应该不是一片黑吧，应该有光标再闪

**Comment by geff86** [comment]
因为没有把etc等demo。exe运行需要的文件夹拷在exe相同的文件夹里。到底需要拷贝那些文件夹参考easypr相关说明文档

**Comment by stq054188** [comment]
请问下，这个问题你们解决了吗，谢谢
