### ISSUE TITLE
如果全蓝色车身+蓝色车牌的奥迪Q5出现了怎么办？

### ISSUE THREAD

**Issue by cpdw840624** [liuruoze/EasyPR#177]
如题。
非常感谢作者这么详尽的文档解释代码，受益匪浅，不过看的时候突然想到这个问题，不知道思路上还有什么可能优化的方向呢？

**Comment by liuruoze** [comment]
比较难办了，碰到这类用颜色和sobel都不好，不过文字定位应该可以解决。
