### ISSUE TITLE
生成、调试有错误

### ISSUE THREAD

**Issue by lkw15183774569** [liuruoze/EasyPR#179]
错误	2	error C1083: 无法打开包括文件: “thirdparty/textDetect/erfilter.hpp”: No such file or directory	C:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	3	1	libeasypr
错误	3	error C1083: 无法打开包括文件: “thirdparty/LBP/lbp.hpp”: No such file or directory	C:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\feature.cpp	3	1	libeasypr
错误	4	error C1083: 无法打开包括文件: “thirdparty/mser/mser2.hpp”: No such file or directory	C:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\core_func.cpp	6	1	libeasypr
错误	6	error C1083: 无法打开包括文件: “thirdparty/xmlParser/xmlParser.h”: No such file or directory	c:\大学计科\毕业设计\识别功能\easypr-easypr-master\easypr\test\accuracy.hpp	12	1	demo
	7	IntelliSense:  无法打开 源 文件 "thirdparty/textDetect/erfilter.hpp"	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	3	1	libeasypr
	8	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	21	66	libeasypr
	9	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	28	7	libeasypr
	10	IntelliSense:  应输入“;”	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	28	20	libeasypr
	11	IntelliSense:  未定义标识符 "er"	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	29	11	libeasypr
	12	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	71	7	libeasypr
	13	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	71	36	libeasypr
	14	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	71	60	libeasypr
	15	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	72	7	libeasypr
	16	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	72	36	libeasypr
	17	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	72	60	libeasypr
	18	IntelliSense:  后面有“::”的名称一定是类名或命名空间名	c:\大学计科\毕业设计\识别功能\easypr-EasyPR-master\EasyPR\src\core\plate_recognize.cpp	74	27	libeasypr

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by BlackSpadeAce** [comment]
@lkw15183774569 
相对路径改一下就好，
`thirdparty/textDetect/erfilter.hpp`
改成
`../thirdparty/textDetect/erfilter.hpp`试一下
