### ISSUE TITLE
使用VS2017 + openCV3.2报错无法打开文件opencv_world300d.lib

### ISSUE THREAD

**Issue by floAlpha** [liuruoze/EasyPR#181]
**Reproduction of the problem**

利用开源EasyPR做车牌识别系统，该系统原本基于opencv3.0，vs2013，而我用的3.2版，vs2017，链接器引用库都填的opencv3.2的，opencv配置正常，排除所有已知错误后提示  无法打开文件opencv_world300d.lib，此错误不能定位 

**Please tell us about your environment:**VS2017& opencv3.2

* **System:** Win 10

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** 3.]2

**Comment by 542447275** [comment]
我也遇到了同样的问题，vs2015+opencv3.1

**Comment by lizzyYL** [comment]
你好！我也遇到了同样的问题 请问你解决了吗？

**Comment by liuruoze** [comment]
opencv_world300d改成opencv_world320d试试吧

**Comment by lizzyYL** [comment]
请问这个支持vs2017+opencv3.1吗 怎么一直有奇怪的问题出现呢？

**Comment by houlei1994** [comment]
我用的vs2015和opencv3.1，也提示这个错误，参照上面的评论，重新配置了opencv，依然提示这个错误。求指导。

**Comment by floAlpha** [comment]
作者你好，我换用opencv3.0编译成功运行，但是测试时提示找不到pdb，无法加载符号

**Comment by houlei1994** [comment]
交流群里给出的解决办法，亲测成功。把lib文件夹下的opencv_world320d.lib复制一个，改名为opencv_world300d.lib。

**Comment by NyikaHE** [comment]
以上所有办法都试过，结果还这样fatal error LNK1181: 无法打开输入文件“opencv_world300d.lib”

**Comment by JingboHu** [comment]
到自己对应的文件夹lib下确认一下是否是opencv_world300d.lib,然后跟vs链接库中输入项对比，看是否一致。两者需保持一致。
