### ISSUE TITLE
最近发现个车牌识别的api

### ISSUE THREAD

**Issue by cpdw840624** [liuruoze/EasyPR#183]
https://www.intelvision.cn/demo/platedetect.shtml
您好，最近发现个车牌识别的api，我想问下，像他这种能够识别车辆型号的是怎么个思路呢？这个车标千差万别，怎么定位呢？不知道有什么思路

**Comment by liuruoze** [comment]
估计用的是深度学习直接将正副图像输入做的车型识别。

**Comment by bingzijian** [comment]
他做的主要是车标识别，我目前借助 @liuruoze 的车牌定位方法，向上方搜寻车标区域做的车标定位，再结合CNN进行训练识别，感谢@liuruoze
