### ISSUE TITLE
OSX opencv 3.2

### ISSUE THREAD

**Issue by hanbim520** [liuruoze/EasyPR#184]
**I'm submitting a ...**  (check one with "x")
  openCV 3.2稍微修改后编译是可以通过的，在运行测试的demo的时候，输入编号有时候会报错，而且基本就是死循环状态了。3.2无法运行任何demo测试。OSX 10.12.4，opencv 3.2 xcode 8.2.1 cmake 3.7.1 gcc Apple LLVM version 8.0.0 (clang-800.0.42.1)

chars_identify.cpp   line 100  ann_->predict(featureRows, output);

在debug模式下 建议采用throw，这样错误比较快的定位。

**Comment by liuruoze** [comment]
应该是etc这个文件夹没有拷贝过去

**Comment by hanbim520** [comment]
车牌识别的我自己弄好了一套，没细致研究这套源码。
