### ISSUE TITLE
能够运行demo 可以进行车牌的检测识别 可是训练SVM时报错 报错如下。请问这是怎么了？谢谢！

### ISSUE THREAD

**Issue by lizzyYL** [liuruoze/EasyPR#185]
////////////////////////////////////
EasyPR Option:
1. 测试;
2. 批量测试;
3. SVM训练;
4. ANN训练;
5. GDTS生成;
6. 开发团队;
7. 感谢名单;
8. 退出;
////////////////////////////////////
请选择一项操作:3
Run "demo svm" for more usage.
>> Collecting train data...
>> Collecting test data...
OpenCV Error: Assertion failed (data) in cv::Mat::at, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\include\opencv2/core/mat.inl.hpp, line 998

* **System:**win10

* **Compiler version/IDE:**VS2015

* **CMake version:** 3.7.2

* **OpenCV version:** 3.2

**Comment by lizzyYL** [comment]
找到了 训练数据集目录对应出错了

**Comment by frozen-l** [comment]
我的也是车牌识别正常但是SVM训练出错，请问你是怎么解决的？
OpenCV Error: Assertion failed (dims <= 2 && data && (unsigned)i0 < (unsigned)(size.p[0] * size.p[1]) && elemSize() == (((((DataType<_Tp>::type) & ((512 - 1) << 3)) >> 3) + 1) << ((((sizeof(size_t)/4+1)*16384|0x3a50) >> ((DataType<_Tp>::type) & ((1 << 3) - 1))*2) & 3))) in cv::Mat::at, file C:\builds\master_PackSlave-win32-vc12-shared\opencv\modules\core\include\opencv2/core/mat.inl.hpp, line 930
