### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by dfelippa** [liuruoze/EasyPR#188]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**
In feature.cpp function getHOGFeatures
does:
HOGDescriptor * hog = new HOGDescriptor(cvSize(128, 64), cvSize(16, 16), cvSize(8, 8), cvSize(8, 8), 3);

There is no delete for that! That will cause a huge memory leak

**Expected/desired behavior**
Replace with:

HOGDescriptor  hog(cvSize(128, 64), cvSize(16, 16), cvSize(8, 8), cvSize(8, 8), 3);
and change pointer by dot

**Comment by liuruoze** [comment]
Thanks for the bug reported
