### ISSUE TITLE
自己训练的ann.xml加载的时候出现异常

### ISSUE THREAD

**Issue by liwenhui1** [liuruoze/EasyPR#191]
我用ann_train训练了一个xml，改名为chinese.xml后，放到model文件夹，启动demo，选择车牌识别，然后就异常了，然后就没有然后了

**Comment by liwenhui1** [comment]
![image](https://cloud.githubusercontent.com/assets/16593793/25223019/c67d8590-25ec-11e7-9c2b-1fc6c30f1f06.png)

**Comment by liwenhui1** [comment]
![image](https://cloud.githubusercontent.com/assets/16593793/25223035/d7a22ce0-25ec-11e7-9150-3c2d584b363f.png)

**Comment by bgJoker** [comment]
为啥我也是出到EasyPR Test之后选择1 没有任何反应呢。。
没有输出。。。只是又循环一遍输出菜单。

**Comment by liuruoze** [comment]
新的版本1.6版本 chinese模型替换为灰度模型，原先的二值化模型不再建议训练了。
