### ISSUE TITLE
precise, recall, fscore 全为0%

### ISSUE THREAD

**Issue by zh-bupt** [liuruoze/EasyPR#193]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**
precise, recall, fscore 全为0%
定位率 NAN
````
请选择一项操作:2
Begin to test the easypr accuracy!
------------------
图片:冀A74110
No ground truth found!
蓝牌:冀A74110 (d)
Recall:0%, Precise:0%, Fscore:0%.
valOstu: 0.96752
valAdap: 0.922377
------------------
图片:黑B99999
No ground truth found!
蓝牌:黑B99999 (d)
Recall:0%, Precise:0%, Fscore:0%.
------------------
Easypr accuracy test end!
------------------
````

**Reproduction of the problem**
100%
**Please tell us about your environment:**

* **System:** OS X 10.12

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.8.0

* **OpenCV version:** [ 3.2 ]

**Comment by liuruoze** [comment]
自己的测试图片需要自己写groundTruth，可以参考EasyPR自带的groundTruth格式
