### ISSUE TITLE
如何安装呢？

### ISSUE THREAD

**Issue by angboontiong** [liuruoze/EasyPR#195]
**I'm submitting a ...**  (check one with "x")
想请问，这个可以在Windows 安装吗？ 还是linux 而已？
如果是Windows，我应该哪里下载？
```
[ ] bug report
[x ] help wanted
[ ] feature request
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by angboontiong79** [comment]
我也希望知道。

**Comment by liuruoze** [comment]
windows: 下载vs2013，然后直接打开sln文件即可，运行Demo程序，然后执行批量测试->general_test就可以看到结果了。
如果想看到图片定位效果，打开accuracy.hpp中，找到pr.setShowResult(false)，改成pr.setShowResult(true)，然后再执行批量测试->general_test即可。

linux和mac: 用cmake来安装：
"""mkdir build
cd build
cmake ..
make -j8
cd ..
./demo
"""

**Comment by liuruoze** [comment]
如果没有其他问题，这个issue就关闭了。
