### ISSUE TITLE
“循环迭代细化”思想处理样本的命令行在新版本里面没有了，怎么办

### ISSUE THREAD

**Issue by happykayy** [liuruoze/EasyPR#196]
文档中有写：
在你运行 EasyPR1.1 版后，在你看到的第一个命令行界面选择
“3.SVM 训练过程”，你就可以看到这些全部的命令。

然而现在运行demo，旋转3，并没有出现命令，请问怎么办？到哪获取1.1版本？

**Comment by liuruoze** [comment]
选择tags即可看到，在release页面也能找到以前的版本
