### ISSUE TITLE
Precise Rate

### ISSUE THREAD

**Issue by mathgameapi** [liuruoze/EasyPR#198]
我在DEMO 跑批量测试, 結果如下
统计参数:
总图片数:257,  Plates count:293,  定位率:90.1024%
Recall:84.1472%, Precise:69.5385%, Fscore:76.1485%.
0-error:60.5691%,  1-error:71.9512%,  Chinese-precise:73.5772%
总时间:399秒,  平均执行时间:1.55253秒

為什麼Precise 只有69.5385% 不是有90% 以上嗎?

**Comment by liuruoze** [comment]
这个Precise是Plate detection评价的指标，说明EasyPR产生了过多的候选车牌，而这些车牌不是真正意义上的车牌。在后续的文字分割步骤，这些负样本的车牌会被进一步筛检。所以这里的值不会代表最终系统的precise。
