### ISSUE TITLE
EasyPR 车牌定位改进

### ISSUE THREAD

**Issue by liuruoze** [liuruoze/EasyPR#2]
使用机器学习方法去改善原来的图像处理的车牌定位模块，plate_locate

**Comment by liuruoze** [comment]
暂时决定参考openalpr的做法，对车牌定位使用更多的调优处理。欢迎有兴趣的同学跟我联系。

**Comment by leiyu1980** [comment]
这部分的确可以参考openalpr，不过haar的速度并不快，特别是针对高清视频。针对高清视频还可以采用前景提取方式减少处理量

**Comment by leiyu1980** [comment]
文字识别部分是不是可以用google那个OCR，识别率是否能更好

**Comment by liuruoze** [comment]
Google的OCR能否识别中文？OCR部分我们已经打算自己来做了。

**Comment by liuruoze** [comment]
不会改变目前的机器学习算法，例如从SVM到haar。只是提取的特征会参考，然后就是车牌检测出来后会进行修正。原始的版本没有这步。

**Comment by liuruoze** [comment]
不会改变目前的机器学习算法，例如从SVM到haar。只是提取的特征会参考，然后就是车牌检测出来后会进行修正。原始的版本没有这步。

**Comment by leiyu1980** [comment]
可以识别中文，并且可以针对某几个中文进行训练

**Comment by xywangah** [comment]
1. 源代码训练库部分样本错误，如3中有B，R中有5，8中有汉字等；
2. 汉字部分建议用SVM，以提高少量汉字样本的识别，如：“海”字。

**Comment by liuruoze** [comment]
@xywangah 第一点已经更正。关于第二点，能否提供更多的证据，SVM比ANN在识别少量汉字上的优异性？其实现在确实存在这样一些问题，某些样本中的训练数量比其他样本多太多了。如果统一每个样本的数量，会不会带来更好的识别效果?

**Comment by liuruoze** [comment]
@leiyu1980  google OCR的地址能否方便给下?

**Comment by leiyu1980** [comment]
http://code.google.com/p/tesseract-ocr/
google 被墙了。可以用这个地址
https://github.com/tesseract-ocr/tesseract

**Comment by liuruoze** [comment]
@leiyu1980  竟然是openalpr也用的，我以前以为它识别不了中文，这么说。openalpr其实也能识别中文车牌咯？

**Comment by leiyu1980** [comment]
是的。只不过我们应该要针对中文车牌做细化处理，比如中文部分就像easyPR就只训练中文，数字部分就只用训练英文和数字的数据来做。openalpr应该是我们要学习的，只不过我们要针对我们的使用环境来做优化，从定位，字符分割，到识别，中文车牌跟其他车牌还是有区别的。。

**Comment by zhoushiwei** [comment]
建议使用hsi颜色来处理看看

发自我的 iPhone

**Comment by c2h2** [comment]
哪里有大量牌照的数据，我想写个东西，aim提升到99% 准确率

**Comment by xywangah** [comment]
您好！
    我用相机、手机拍摄了很多车牌，并进行了分辨率转换。另外，在网上也收集了大量车牌照片，遗憾的是：
EasyPR 在车牌定位校正、字符分割、字符识别等方面处理相对简单，要提高识别率很困难。另外，不同分
辨率车牌图像笔划粗细差别很大，我进行了一些改进，效果也提高有限。准备开学后同高校合作，在车牌定位、
字符分割和识别方面进行全面提升。     




xywangah@126.com

发件人： Yiling Cao
发送时间： 2015-02-27 00:03
收件人： liuruoze/EasyPR
抄送： xywangah
主题： Re: [EasyPR] EasyPR 车牌定位改进 (#2)
哪里有大量牌照的数据，我想写个东西，aim提升到99% 准确率

**Comment by ahccom** [comment]
cnn识别字符效果很不错
https://github.com/nyanp/tiny-cnn

**Comment by liuruoze** [comment]
在 v1.2版本中对定位做了大量改进。对定位的下一步改进建议再起一个新帖子。

**Comment by xywangah** [comment]
1.2 版定位的确有提高，但在车牌定位样本测试时发现：
（1） 对颜色褪色车牌定位不好；
（2）识别率对阴天车牌定位不好；
建议：
（1） 在工程中增加车牌定位区域参数，便于外部界面接口；
（2） 在工程中增加应用程序路径参数，否则易导致模型、存储等文件路径模糊；
（3） 界面与功能分离，影响功能集成测试 。

**Comment by liuruoze** [comment]
定位改善功能暂时不更新，目前阶段集中在字符识别提升部分。
针对这三个advise，建议每个单独起一个Pull request，说明方式参考 #19。我这边测试后合并。
