### ISSUE TITLE
如何得到ANN训练所需样本的灰度图？

### ISSUE THREAD

**Issue by happykayy** [liuruoze/EasyPR#200]
我想扩充ANN训练的样本集，该样本集是灰度图。
我使用字符分割模块后，想将得到的图作为训练的样本，但得到的图都是二值图。这样一来，如何扩充灰度图的样本集呢？

**Comment by liuruoze** [comment]
程序中有提取灰度字符的代码，可以参考中文字符是如何提取灰度图的。
