### ISSUE TITLE
“free大神车牌集里提取字符”请问该方法在哪里？

### ISSUE THREAD

**Issue by happykayy** [liuruoze/EasyPR#201]
你好，
1、在群里发布的新版更新之处其中有一点：“并且在主界面中提供了一个方法从free大神的车牌集里提取中文与英文字符”，请问该方法在哪里？控制台上面应该选择那一项？
2、另外，accuracyCharRecognizeTest函数将读取plates_200k文件夹下的图片，然而并没有该文件夹？该函数的作用是？

**Comment by liuruoze** [comment]
这个方法应该是对应第6项，也就是调用accuracyCharRecognizeTest()函数。plate_200k就是存放Free提供的数据集的，大概200k张图片左右。

由于版权原因，这个数据集EasyPR并不提供。如果想要得到的话可以加群问人，运气好的话应该可以得到。这个数据集是严禁用于商业目的的！
