### ISSUE TITLE
直接克隆最新版本EasyPR在WIN10系统下，在VS2013X64平台无法编译运行，在WIN32平台下可以编译运行

### ISSUE THREAD

**Issue by ZhaoQiang2015** [liuruoze/EasyPR#202]
我直接在官网克隆了最新版的EasyPR主分支，然后放到我的VS2013中运行，在X64平台下可以生成，无法运行，而在WIN32平台下，可以生成也可以运行。OpenCV版本为3.0，属性配置我都对应完成了，我的系统是WIN10，请问有其它人碰到这个问题吗？有没有什么解决方案？谢谢。

**Comment by codevvvv9** [comment]
你是demo运行成功了么？

**Comment by codevvvv9** [comment]
@ZhaoQiang2015

**Comment by ZhaoQiang2015** [comment]
该问题已解决，我使用了OpenCV3.1版本进行编译，可以编译运行demo。@codevvvv9
