### ISSUE TITLE
想用1.6版本里面博客里面显示的图形化版本，但是demo运行一直在命令行运行啊

### ISSUE THREAD

**Issue by codevvvv9** [liuruoze/EasyPR#206]
**看了以前回答说调用libeasypr的api可以，但是看不懂这句话啊** 

**希望作者可以写一个简略的文档，作为使用手册**

毕竟有很多像我一样刚入门的小白，终于配置好了，demo运行正常，但是不能自己改造好尴尬，如果有了文档就可以啦，谢谢博主啦

* **System:** win7

* **Compiler version/IDE:** VS 2013

* **OpenCV version:** 3.1

**Comment by liuruoze** [comment]
readme里的示例中有pr.setResultShow(false); 改成true即可看到图形结果。

开发文档可以看博客里的介绍。
