### ISSUE TITLE
cmake版本不够引起编译失败

### ISSUE THREAD

**Issue by sunnyczh1** [liuruoze/EasyPR#207]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by liuruoze** [comment]
这个原因是cmake需要的版本和你的版本不匹配。这个错误很好解决，打开CMakeLists.txt这个文件，把 CMake 3.1.0 or higher is required中的版本号改成你的版本号。
