### ISSUE TITLE
编译报错：/home/cfs/c++_opecv/EasyPR-master/src/core/chars_identify.cpp: 在构造函数‘easypr::CharsIdentify::CharsIdentify()’中: /home/cfs/c++_opecv/EasyPR-master/include/easypr/config.h:145:42: 错误：expected primary-expression before ‘>’ token      model = ml::ANN_MLP::load<ml::ANN_MLP>(path);                                           ^ /home/cfs/c++_opecv/EasyPR-master/src/core/chars_identify.cpp:22:3: 附注：in expansion of macro ‘LOAD_ANN_MODEL’    LOAD_ANN_MODEL(ann_, kDefaultAnnPath);    ^

### ISSUE THREAD

**Issue by sunnyczh1** [liuruoze/EasyPR#208]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by liuruoze** [comment]
这个应该是不可见的字符导致的编译错误，请仔细检查这部分代码是否有格式上的问题。

**Comment by lyymoo** [comment]
修改：/root/EasyPR-master/include/easypr/config.h
注释下记代码：
/*
#ifdef CV_VERSION_THREE_TWO
  #define LOAD_SVM_MODEL(model, path) \
    model = ml::SVM::load(path);
  #define LOAD_ANN_MODEL(model, path) \
    model = ml::ANN_MLP::load(path);
#else
  #define LOAD_SVM_MODEL(model, path) \
    model = ml::SVM::load<ml::SVM>(path);
  #define LOAD_ANN_MODEL(model, path) \
    model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
#endif
*/
添加下记代码：
#define LOAD_SVM_MODEL(model, path) \
    model = ml::SVM::load(path);
#define LOAD_ANN_MODEL(model, path) \
    model = ml::ANN_MLP::load(path);
