### ISSUE TITLE
刘总您好，请教您一个问题

### ISSUE THREAD

**Issue by coldcold** [liuruoze/EasyPR#209]
我是java开发，测试了java版本的，很多车牌会读取错误（比如 汉字识别错误），大图也无法识别。所以想测试下c++版本的，毕竟10几天前还有更新。  但是我对c++一窍不通，想法很简单，只是写个接口，拿到结果就好。   但是遇到一个问题，无法生成demo.exe。我生成解决方法，提示错误如下：

error C1083: 无法打开源文件：“..\src\preprocess\mc_data.cpp”:No such file or directory
error C1083: 无法打开包括文件：“thirdparty/textDetect/erfilter.hpp”:No such file or directory
......

请求帮助，非常感谢！

**Comment by liuruoze** [comment]
这几个文件都在最新的1.6版本删除了，你只需要打开生成的脚本，把这些文件删去就可以了，不影响功能的使用。

**Comment by coldcold** [comment]
非常感谢！我去试试~

**Comment by coldcold** [comment]
EasyPR/src/core/core_func.cpp文件中 #include "thirdparty/mser/mser2.hpp"
这个头文件引用的路径是不是有点问题...

**Comment by cnmoko** [comment]
改成： #include "../thirdparty/mser/mser2.hpp"就好了

**Comment by coldcold** [comment]
谢谢 @cnmoko
