### ISSUE TITLE
调用libeasypr.a是出现问题

### ISSUE THREAD

**Issue by newzhx** [liuruoze/EasyPR#212]
想基于easypr做二次开发，在工程里调用libeasypr.so。
但是一旦添加#include<easypr.h>，工程里另外一个动态库就会报错，找不到opencv_highgui中的一个符号函数，去掉easypr相关代码，编译通过。请问这是什么问题？

**Please tell us about your environment:**

* **System:** ubuntu14.04

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** 3.1

**Comment by liuruoze** [comment]
这个问题依然存在么？这个issue先被关闭了。如果还有问题，可以open它。
