### ISSUE TITLE
有没有谁将工程迁移到 Xcode 上的

### ISSUE THREAD

**Issue by zh-bupt** [liuruoze/EasyPR#213]
**I'm asking for help**  (check one with "x")

```
[ ] bug report
[x] help wanted
[ ] feature request
```
**有没有谁将工程迁移到 Xcode 上的**

**Please tell us about your environment:**

* **System:** Mac OSX 10.12

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [ 3.2 ]

**Comment by liuruoze** [comment]
在mac下用Clion引入所有文件，再使用easypr自带的cmakelist即可顺利编译
