### ISSUE TITLE
遇到几个错误

### ISSUE THREAD

**Issue by RogerCV** [liuruoze/EasyPR#214]
错误	C1083	无法打开源文件: “..\src\preprocess\mc_data.cpp”: No such file or directory	libeasypr	D:\EasyPR\vcprojs\c1xx	1	
错误	C1083	无法打开源文件: “..\src\preprocess\gdts.cpp”: No such file or directory	libeasypr	D:\EasyPR\vcprojs\c1xx	1	
错误	C1083	无法打开源文件: “..\src\preprocess\deface.cpp”: No such file or directory	libeasypr	D:\EasyPR\vcprojs\c1xx	1	
错误	C1083	无法打开源文件: “..\src\core\plate.cpp”: No such file or directory	libeasypr	D:\EasyPR\vcprojs\c1xx	1	

错误	LNK1104	无法打开文件“D:\EasyPR\libeasypr.lib”	demo	D:\EasyPR\vcprojs\LINK	1	

VS2015

**Comment by liuruoze** [comment]
这些文件在新的1.6版已经删除了，你可以在配置中删除这些引用的文件，不影响系统正常运行。
