### ISSUE TITLE
想知道一个小白问题。训练了SVM，识别一张百度找来的车牌照片并没有结果

### ISSUE THREAD

**Issue by xiaoheiAh** [liuruoze/EasyPR#218]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ ] help wanted
[ ] feature request
```

**这是为什么呢?**
**Current behavior**
![image](https://cloud.githubusercontent.com/assets/27981726/26542935/71172b72-448e-11e7-9af7-e6f9c4b2ef3d.png)

**Expected/desired behavior**

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** Linux Mint

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by liuruoze** [comment]
新版本的model都放在了model文件夹，不再是resources/model。usage.md里的介绍暂时还没有更新。
