### ISSUE TITLE
求linux编译方法

### ISSUE THREAD

**Issue by ericdum** [liuruoze/EasyPR#22]
因为不怎么懂C++，也没有windows的VC环境，求教如何在linux或者mac下编译

**Comment by Micooz** [comment]
以Linux为例，mac基本一致。
1. 安装最新版本的CMake。
2. 下载opencv for linux源代码。
3. 使用CMake工具编译opencv。
4. make install opencv库到默认位置。
5. 下载项目代码。
6. 使用CMake编译项目即可。

**Comment by ericdum** [comment]
谢谢，我用yum装了opencv 2.0编译报错如下。

我现在下2.4的源码试试，应该没啥大问题，谢谢了

```
/var/www/easypr/EasyPR/src/include/prep.h:5:39: error: opencv2/imgproc/imgproc.hpp: No such file or directory
/var/www/easypr/EasyPR/src/include/prep.h:6:39: error: opencv2/highgui/highgui.hpp: No such file or directory
/var/www/easypr/EasyPR/src/include/prep.h:7:42: error: opencv2/nonfree/features2d.hpp: No such file or directory
```

**Comment by ericdum** [comment]
还是报错，求解
```
fatal error: 'opencv2/imgproc/imgproc.hpp'      file not found
```

**Comment by ericdum** [comment]
我知道了，先试试

**Comment by ericdum** [comment]
还是搞不定，mac报上面的错，Red Hat opencv就编不过

**Comment by liuruoze** [comment]
看来主要问题还是opecncv编译的问题，先在网上找下教程，看看linux编译的过程？
我有过一次在linux编译opencv的经历，但是以失败告终，所以在这个问题上没有啥发言权。
还是请 @Micooz 帮你解答问题更好点。

或者装一个windows虚拟机，这也是一种可行的解决方案。

**Comment by Micooz** [comment]
c++: Internal error: Killed (program cc1plus) 

网络上相关的解释是内存不足引起的编译中断。

**Comment by liuruoze** [comment]
@ericdum 请问这个问题最后解决了么？如果没有解决，还需要我们这边什么帮助？

**Comment by ericdum** [comment]
@liuruoze 还是没解决，其实如果能有个编译好的在mac和red hat下可以执行的文件就可以。接受一个图片路径，然后吐出一个或多个车牌。

**Comment by liuruoze** [comment]
你是要程序还是要二次开发？如果要程序的话，可以私信我们开发人员，要一个静态编译的程序即可。不过目前的EasyPR用作商用恐怕还有很远的距离。
