### ISSUE TITLE
汉字识别正确率低

### ISSUE THREAD

**Issue by jenopob** [liuruoze/EasyPR#220]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] help wanted
[ ] feature request
```

是否需要进行相关的机器学习过程？或者其他途径来稳定识别率，或者调整本身的一些配置项
字符编码相关的配置？

识别案例：
苏B 21G86 识别后 变成渝621G86
苏B 588N6 识别后 变成甘B588N6

**Please tell us about your environment:**

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.2.1

* **OpenCV version:** [3.1 ]

**Comment by jenopob** [comment]
我也尝试[https://github.com/liuruoze/EasyPR/blob/master/Usage.md](url)
按照里面介绍的SVM训练，ANN训练进行了实际操作，替换原来的ann.xml svm.xml

但识别返回都是空

**Comment by moonsummer** [comment]
你是怎么解决汉子识别率低的？我遇到这个问你题

**Comment by liuruoze** [comment]
下一个版本将努力强化汉字识别
