### ISSUE TITLE
VS2013编译错误

### ISSUE THREAD

**Issue by baiyygtfj** [liuruoze/EasyPR#226]
LOAD_SVM_MODEL(svm_, svm_xml_);
错误	1	error C2275: “cv::ml::SVM”: 将此类型用作表达式非法	c:\easypr-master\src\train\svm_train.cpp	68	1 libeasypr
错误	2	error C2275: “cv::ml::SVM”: 将此类型用作表达式非法	c:\easypr-master\src\core\plate_judge.cpp	20	1 libeasypr
错误	3	error C2275: “cv::ml::SVM”: 将此类型用作表达式非法	c:\easypr-master\src\core\plate_judge.cpp	24	1 libeasypr
错误	4	error C2275: “cv::ml::SVM”: 将此类型用作表达式非法	c:\easypr-master\src\core\plate_judge.cpp	33	1 libeasypr
LOAD_ANN_MODEL(ann_, path);
错误	5	error C2275: “cv::ml::ANN_MLP”: 将此类型用作表达式非法	c:\easypr-master\src\core\chars_identify.cpp	22	1	libeasypr
错误	6	error C2275: “cv::ml::ANN_MLP”: 将此类型用作表达式非法	c:\easypr-master\src\core\chars_identify.cpp	23	1	libeasypr
错误	7	error C2275: “cv::ml::ANN_MLP”: 将此类型用作表达式非法	c:\easypr-master\src\core\chars_identify.cpp	24	1	libeasypr
错误	8	error C2275: “cv::ml::ANN_MLP”: 将此类型用作表达式非法	c:\easypr-master\src\core\chars_identify.cpp	36	1	libeasypr
错误	9	error C2275: “cv::ml::ANN_MLP”: 将此类型用作表达式非法	c:\easypr-master\src\core\chars_identify.cpp	44	1	libeasypr
错误	10	error C2275: “cv::ml::ANN_MLP”: 将此类型用作表达式非法	c:\easypr-master\src\core\chars_identify.cpp	52	1	libeasypr

**Comment by liuruoze** [comment]
opencv3.2带来的编译错误，具体可参照在readme里的介绍，在config.h里增加宏定义来解决这个问题。
