### ISSUE TITLE
void getColorFeatures(const Mat& src, Mat& features)这个有什么用?

### ISSUE THREAD

**Issue by tiger822** [liuruoze/EasyPR#227]
**I'm submitting a ...**  (check one with "x")
[ ] help wanted
在svm训练的代码里面有void getColorFeatures(const Mat& src, Mat& features)这个, 
请问有什么作用?

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** 3.2

**Comment by liuruoze** [comment]
这个是用来提取基于颜色的特征的，作为svm判断的一个feature，深入可以看代码了解。
