### ISSUE TITLE
训练后的Test得分并没达到 98?

### ISSUE THREAD

**Issue by tiger822** [liuruoze/EasyPR#228]
>> Your SVM Model was saved to tmp/svm.xml
>> Testing...
count_all: 2332
ptrue_rtrue: 475
ptrue_rfalse: 92
pfalse_rtrue: 42
pfalse_rfalse: 1723
precise: 0.837743
recall: 0.918762
Fsocre: 0.876384

[ ] help wanted
* **System:**  win10

* **Compiler version/IDE:** vs2017, x64 debug mode

* **OpenCV version:**  3.2

**Comment by liuruoze** [comment]
嗯，新版本的svm的test数据和博客时版本不一样了。目前的test数据会比博客里的时期难很多，虽然svm模型与特征得到了改善，但总体的得分还是下降。
