### ISSUE TITLE
ERROR: compile main.cpp in the test directory? How to compile it correctly? How to use the static library?

### ISSUE THREAD

**Issue by miversoness** [liuruoze/EasyPR#229]
```
[ ] bug report
[ ] help wanted
[ ] feature request
```

**Current behavior**
miven@inspur-01:~/project/EasyPR/test$ g++ main.cpp -std=c++11 -l /home/miven/project/EasyPR/_build/libeasypr.a -o main
In file included from /home/miven/project/EasyPR/include/easypr/core/plate_detect.h:5:0,
                 from /home/miven/project/EasyPR/include/easypr/core/plate_recognize.h:15,
                 from /home/miven/project/EasyPR/include/easypr.h:4,
                 from main.cpp:1:
/home/miven/project/EasyPR/include/easypr/core/plate_judge.h:31:11: error: ‘ml’ was not declared in this scope
   cv::Ptr<ml::SVM> svm_;
           ^
/home/miven/project/EasyPR/include/easypr/core/plate_judge.h:31:18: error: template argument 1 is invalid
   cv::Ptr<ml::SVM> svm_;
                  ^
In file included from /home/miven/project/EasyPR/include/easypr/core/chars_recognise.h:16:0,
                 from /home/miven/project/EasyPR/include/easypr/core/plate_recognize.h:16,
                 from /home/miven/project/EasyPR/include/easypr.h:4,
                 from main.cpp:1:
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:45:11: error: ‘ml’ is not a member of ‘cv’
   cv::Ptr<cv::ml::ANN_MLP> ann_;
           ^
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:45:11: error: ‘ml’ is not a member of ‘cv’
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:45:26: error: template argument 1 is invalid
   cv::Ptr<cv::ml::ANN_MLP> ann_;
                          ^
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:48:11: error: ‘ml’ is not a member of ‘cv’
   cv::Ptr<cv::ml::ANN_MLP> annChinese_;
           ^
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:48:11: error: ‘ml’ is not a member of ‘cv’
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:48:26: error: template argument 1 is invalid
   cv::Ptr<cv::ml::ANN_MLP> annChinese_;
                          ^
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:51:11: error: ‘ml’ is not a member of ‘cv’
   cv::Ptr<cv::ml::ANN_MLP> annGray_;
           ^
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:51:11: error: ‘ml’ is not a member of ‘cv’
/home/miven/project/EasyPR/include/easypr/core/chars_identify.h:51:26: error: template argument 1 is invalid
   cv::Ptr<cv::ml::ANN_MLP> annGray_;
                          ^
In file included from /home/miven/project/EasyPR/include/easypr/core/chars_recognise.h:17:0,
                 from /home/miven/project/EasyPR/include/easypr/core/plate_recognize.h:16,
                 from /home/miven/project/EasyPR/include/easypr.h:4,
                 from main.cpp:1:
/home/miven/project/EasyPR/include/easypr/core/core_func.h:63:18: error: ‘LINE_8’ was not declared in this scope
   int lineType = LINE_8, int shift = 0);
                  ^
In file included from /home/miven/project/EasyPR/include/easypr/train/svm_train.h:4:0,
                 from /home/miven/project/EasyPR/include/easypr.h:5,
                 from main.cpp:1:
/home/miven/project/EasyPR/include/easypr/train/train.h:19:19: error: ‘ml’ is not a member of ‘cv’
   virtual cv::Ptr<cv::ml::TrainData> tdata() = 0;

**I'm submitting a ...**  (check one with "x")

**Expected/desired behavior**

**Reproduction of the problem**

If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** CentOS

* **Compiler version/IDE:** gcc4.8

* **CMake version:** 3.5.1

* **OpenCV version:** [2.4.9 | 2.4.10 | 2.4.11 | 2.4.12 | 2.4.13 | 3.0 ALPHA | 3.0 BETA | 3.0 RC1 | 3.0 | 3.1 ]

**Comment by liuruoze** [comment]
直接执行 ./build.sh就可以编译全部成功，不要单独编译。

**Comment by miversoness** [comment]
我需要只调用后面的字符识别的类，但是自己写的代码总是说调用有错（我是用-L 指定静态链接的），所有就想自己编译一下test文件夹，发现还是有错，请问有什么办法么
