### ISSUE TITLE
无法打开输入文件libeasypr.lib

### ISSUE THREAD

**Issue by 81BlingBling18** [liuruoze/EasyPR#231]
编译时提示

错误	LNK1181	无法打开输入文件“C:\Users\wqm\Documents\EP\EasyPR\x64\Debug\libeasypr.lib”	demo	C:\Users\wqm\Documents\EP\EasyPR\vcprojs\LINK	1

这个文件在debug目录中是不存在的

**Please tell us about your environment:**

* **System:** win10

* **VS版本:**2015 community

**Comment by devoteasecond** [comment]
出现此问题说明libeasypr没有正确生成，请调整其编译属性
demo依赖于libeasypr
祝好
