### ISSUE TITLE
编译出错，请各位大牛指导啊！

### ISSUE THREAD

**Issue by qinzhijun99** [liuruoze/EasyPR#232]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x ] help wanted
[ ] feature request
```

**Current behavior**
编译不成功

**Expected/desired behavior**
编译成功

**Reproduction of the problem**

Run ./build.sh  显示如下信息：

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found suitable version "3.2.0", minimum required is "3.2.0") 
-- Found OpenCV: /usr/local (found suitable version "3.2.0", minimum required is "3.1.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhijun/EasyPR-master/build
Scanning dependencies of target thirdparty
Scanning dependencies of target easypr
[  3%] Building CXX object thirdparty/CMakeFiles/thirdparty.dir/xmlParser/xmlParser.cpp.o
[  7%] Building CXX object thirdparty/CMakeFiles/thirdparty.dir/LBP/helper.cpp.o
[ 11%] Building CXX object thirdparty/CMakeFiles/thirdparty.dir/mser/mser2.cpp.o
[ 14%] Building CXX object thirdparty/CMakeFiles/thirdparty.dir/LBP/lbp.cpp.o
[ 18%] Building CXX object thirdparty/CMakeFiles/thirdparty.dir/textDetect/erfilter.cpp.o
[ 22%] Building CXX object CMakeFiles/easypr.dir/src/core/core_func.cpp.o
[ 25%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_recognise.cpp.o
[ 29%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o
[ 33%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_segment.cpp.o
[ 37%] Building CXX object CMakeFiles/easypr.dir/src/core/feature.cpp.o
[ 40%] Building CXX object CMakeFiles/easypr.dir/src/core/plate_detect.cpp.o
In file included from /home/zhijun/EasyPR-master/include/easypr/core/plate.hpp:15:0,
                 from /home/zhijun/EasyPR-master/include/easypr/core/core_func.h:5,
                 from /home/zhijun/EasyPR-master/src/core/chars_identify.cpp:3:
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp: In constructor ‘easypr::CharsIdentify::CharsIdentify()’:
/home/zhijun/EasyPR-master/include/easypr/config.h:143:42: error: expected primary-expression before ‘>’ token
     model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                          ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp:22:3: note: in expansion of macro ‘LOAD_ANN_MODEL’
   LOAD_ANN_MODEL(ann_, kDefaultAnnPath);
   ^
/home/zhijun/EasyPR-master/include/easypr/config.h:143:42: error: expected primary-expression before ‘>’ token
     model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                          ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp:23:3: note: in expansion of macro ‘LOAD_ANN_MODEL’
   LOAD_ANN_MODEL(annChinese_, kChineseAnnPath);
   ^
/home/zhijun/EasyPR-master/include/easypr/config.h:143:42: error: expected primary-expression before ‘>’ token
     model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                          ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp:24:3: note: in expansion of macro ‘LOAD_ANN_MODEL’
   LOAD_ANN_MODEL(annGray_, kGrayAnnPath);
   ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadModel(std::__cxx11::string)’:
/home/zhijun/EasyPR-master/include/easypr/config.h:143:42: error: expected primary-expression before ‘>’ token
     model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                          ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp:36:5: note: in expansion of macro ‘LOAD_ANN_MODEL’
     LOAD_ANN_MODEL(ann_, path);
     ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadChineseModel(std::__cxx11::string)’:
/home/zhijun/EasyPR-master/include/easypr/config.h:143:42: error: expected primary-expression before ‘>’ token
     model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                          ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp:44:5: note: in expansion of macro ‘LOAD_ANN_MODEL’
     LOAD_ANN_MODEL(annChinese_, path);
     ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadGrayChANN(std::__cxx11::string)’:
/home/zhijun/EasyPR-master/include/easypr/config.h:143:42: error: expected primary-expression before ‘>’ token
     model = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                          ^
/home/zhijun/EasyPR-master/src/core/chars_identify.cpp:52:5: note: in expansion of macro ‘LOAD_ANN_MODEL’
     LOAD_ANN_MODEL(annGray_, path);
     ^
CMakeFiles/easypr.dir/build.make:86: recipe for target 'CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o' failed
make[2]: *** [CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/easypr.dir/all' failed
make[1]: *** [CMakeFiles/easypr.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 44%] Linking CXX static library libthirdparty.a
[ 44%] Built target thirdparty
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **System:** Ubuntu16.04 LTS

* **Compiler version/IDE:** gcc5.4.0

* **CMake version:** 3.5.1

* **OpenCV version:** [3.2 ]

**Comment by liuruoze** [comment]
看一下readme里介绍的怎么解决opencv3.2编译问题的方法

**Comment by newdee** [comment]
Readme并没有看到啊～
@liuruoze

**Comment by liuruoze** [comment]
对于Opencv3.2或以上版本，如果碰到编译问题，例如“ANN_MLP”相关的错误，尝试将config.h中将#define CV_VERSION_THREE_ZERO改为#define CV_VERSION_THREE_TWO试试. @newdee , 再试试看

**Comment by xinlnix** [comment]
> 对于Opencv3.2或以上版本，如果碰到编译问题，例如“ANN_MLP”相关的错误，尝试将config.h中将#define CV_VERSION_THREE_ZERO改为#define CV_VERSION_THREE_TWO试试. @newdee , 再试试看

thanks,It worked for me on opencv4
