### ISSUE TITLE
编译得到demo.exe之后运行出错

### ISSUE THREAD

**Issue by fongdier** [liuruoze/EasyPR#234]
运行环境：
win7 + vs2013 + opencv3.2.0

编译通过后，得到demo.exe文件，将/bin目录配置至path中，双击运行，出现debug error R6010 abort() has been called .指向 main.cpp 的 
int main(int argc, const char* argv[]) {
  std::shared_ptr<easypr::Kv> kv(new easypr::Kv);
  kv->load("resources/text/chinese_mapping");
位置。

**Comment by liuruoze** [comment]
kv文件没有找到/text/chinese_mapping， 尝试不要配置path，直接在运行demo.exe

**Comment by Pichairen** [comment]
将resources文件拷贝到debug目录下？我也还没解决
