### ISSUE TITLE
问一下 ann_chinese.xml是从哪些样本训练出来的

### ISSUE THREAD

**Issue by xufunly** [liuruoze/EasyPR#235]
非常感谢EasyPR的工程，我做了尝试，其它几个model可以训练。
ann_chinese.xml是从哪部分样本训练的，能否给个说明。
谢谢！

**Comment by IcecrownGlacier** [comment]
@xufunly 请问楼主您那边解决了这个问题了吗？我也遇到了同样的问题。

**Comment by liuruoze** [comment]
可以看下新的Useage.md最后面几行，已有解释。
