### ISSUE TITLE
assert reader failed

### ISSUE THREAD

**Issue by ghgggg** [liuruoze/EasyPR#236]
my program build is ok，but execution failed and give me a message “Assertion failed: reader, file ..\src\util\kv.cpp, line 11”
why ？

**Please tell us about your environment:**

* **System:**windows 10

* **Compiler version/IDE: vs2013

* **OpenCV version:** [ 3.1 ]

**Comment by liuruoze** [comment]
这个应该是由于没有读取到model文件夹下的province_mapping文件或者text文件夹下的chinese_mapping文件导致的。检查一下文件路径。
如果问题依然存在，open这个issue。

**Comment by Meraing** [comment]
我也是这个问题，demo可以运行，但是同解决方案下的新建项目或者另外新建解决方案都会出这个错。如果我在config.h中改成绝对路径又会在chars_identify.cpp的ann_->predict(featureRows, output);这步出错。
请问model文件夹的路径应该在哪里或者怎么指定？

**Comment by xuanfengchen** [comment]
我刚刚解决了这个问题，点击项目的属性，把工作目录改为和demo一样设置即可

**Comment by Donald-Su** [comment]
我也出现了这个问题，是因为demo.exe没在EasyPR根目录下的原因导致的，把编译好的demo.exe拷贝到EasyPR根目录问题解决。

供参考~
