### ISSUE TITLE
opencv3.2+easypr1.6 android编译，出现错误  multiple definition of 'cv::ml::SVM::getDefaultGrid(int)'

### ISSUE THREAD

**Issue by Virczz** [liuruoze/EasyPR#237]
**I'm submitting a ...**  (check one with "x")

```
[ x] help wanted
```

**Current behavior**
![error](https://user-images.githubusercontent.com/15669121/28815029-7e1abe08-76d2-11e7-9c03-5daa9c50e165.png)

**Expected/desired behavior**
我将opencv3.2.0和easyPR1.6导入到Android工程以后，已经基本编译成功。但是会在如图所示的两个函数处出现该错误。我想请教下，你们在VS或者linux里面编译时，这个位置会出错吗？c++新手，请求帮助。

**Please tell us about your environment:**

* **System:** Windows 

* **Compiler version/IDE:** Android Studio 2.2.3

* **CMake version:** 3.5.1

* **OpenCV version:** [3.2.0 ]

**Comment by xieliang** [comment]
想移植到android平台？ 可以参考 https://github.com/linuxxx/EasyPR_Android  不过这个项目好像最新没更新，还是基于老的EasyPR1.4代码做的。
如果只是demo玩玩，可以试试 https://github.com/xieliang/EasyPR_Android  小弟这周临时折腾的，基于最新EasyPR1.6alpha，不过我之前没做过android开发，所以android app相关代码可以忽视先：）
