### ISSUE TITLE
Ubuntu16编译失败

### ISSUE THREAD

**Issue by wartih** [liuruoze/EasyPR#241]
你好，我是初学者
在1.5版本中ubuntu16下运行build.sh
会出现：
/root/EasyPR-1.5/src/core/chars_identify.cpp:20:41: error: expected primary-expression before ‘>’ token
     ann_ = ml::ANN_MLP::load<ml::ANN_MLP>(kDefaultAnnPath);
                                         ^
/root/EasyPR-1.5/src/core/chars_identify.cpp:21:48: error: expected primary-expression before ‘>’ token
     annChinese_ = ml::ANN_MLP::load<ml::ANN_MLP>(kChineseAnnPath);
                                                ^
/root/EasyPR-1.5/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadModel(std::__cxx11::string)’:
/root/EasyPR-1.5/src/core/chars_identify.cpp:32:43: error: expected primary-expression before ‘>’ token
       ann_ = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                           ^
/root/EasyPR-1.5/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadChineseModel(std::__cxx11::string)’:
/root/EasyPR-1.5/src/core/chars_identify.cpp:42:50: error: expected primary-expression before ‘>’ token
       annChinese_ = ml::ANN_MLP::load<ml::ANN_MLP>(path);
                                                  ^
CMakeFiles/easypr.dir/build.make:86: recipe for target 'CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o' failed
make[2]: *** [CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o] Error 1

谢谢~

**Comment by ericsimith** [comment]
你应该提供自己的环境，比如你的OpenCV的版本，再比如说你是否按照要求修改你的cmakefile.txt，你的config.h有没有修改等等。
这里我估计就是OpenCV版本，你没有修改cmakefile.txt和config.h的原因
建议你认真阅读usage.md文件

**Comment by behind47** [comment]
Hello, I'm a newer for EasyPR and it occurred to me the same problem as yours. The error info is as follows:

> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp: In constructor ‘easypr::CharsIdentify::CharsIdentify()’:
> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp:20:41: error: expected primary-expression before ‘>’ token
>      ann_ = ml::ANN_MLP::load\<ml::ANN_MLP>(kDefaultAnnPath);
>                                          ^
> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp:21:48: error: expected primary-expression before ‘>’ token
>      annChinese_ = ml::ANN_MLP::load\<ml::ANN_MLP>(kChineseAnnPath);
>                                                 ^
> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadModel(std::string)’:
> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp:32:43: error: expected primary-expression before ‘>’ token
>        ann_ = ml::ANN_MLP::load\<ml::ANN_MLP>(path);
>                                            ^
> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp: In member function ‘void easypr::CharsIdentify::LoadChineseModel(std::string)’:
> /home/admin/EasyPR/EasyPR/src/core/chars_identify.cpp:42:50: error: expected primary-expression before ‘>’ token
>        annChinese_ = ml::ANN_MLP::load\<ml::ANN_MLP>(path);
>                                                   ^
> make[2]: *** [CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o] Error 1
> make[1]: *** [CMakeFiles/easypr.dir/all] Error 2
> make: *** [all] Error 2

The version of OpenCV is 3.1.0-dev, and I have modified it's path in CMakeLists.txt according to Usage.md. The version of gcc is 4.8.4-2, EasyPR is v1.5, OS is ubuntu14.04.3.

I deleted all code segments in error info such as '<ml::ANN_MLP>' and ends compiling with no error. I'll appreciate it if you can share your solutions to this problem.

**Comment by newdee** [comment]
I meet the same problem, the ANN_model and the svm model can not make correctly 
and the demo always core dump
