### ISSUE TITLE
调用plateRecognize接口引起崩溃的问题

### ISSUE THREAD

**Issue by carmanlwf** [liuruoze/EasyPR#242]
直接利用 EasyPR/include 和编译生成的静态库来调用EasyPR提供的函数接口编写自己的程序

- **I'm

  直接利用 EasyPR/include 和编译生成的静态库来调用EasyPR提供的函数接口编写自己的demo程序

``` c++
	CPlateRecognize pr;
	pr.setResultShow(true);
	pr.setDetectType(PR_DETECT_CMSER);
	pr.setMaxPlates(4);
	vector<CPlate> plateVec;
	Mat src = imread("pic.jpg");
	//namedWindow("游戏原画");
	// 在窗口中显示游戏原画  
       //imshow("游戏原画",src);
	int result = pr.plateRecognize(src, plateVec);
	cout << "result" << result << endl;
	if (!result) 
	{
		for (int i = 0; i < plateVec.size(); ++i)
		{
			CPlate plate = plateVec.at(i);
			Mat plateMat = plate.getPlateMat();
			RotatedRect rrect = plate.getPlatePos();
			string license = plate.getPlateStr();
			cout << license << "i" << i << endl;
		}
	}
```
在调试的时候 发现调用plateRecognize接口引起崩溃的问题
![1](https://user-images.githubusercontent.com/23070026/29648964-d5be81a0-88c3-11e7-8d9f-258d16ddfb9e.png)

**Please tell us about your environment:**

* **System:** win7 64

* **Compiler version/IDE:** vs2015

* **CMake version:** 3.9.1

* **OpenCV version:** 3.3

**Comment by liuruoze** [comment]
这是由于kv没有发现province_mapping文件导致的，将model文件夹复制过去，应该可以解决问题。
