### ISSUE TITLE
vs2015 libeasypr 编译时候 C2275 'cv::ml::SVM': illegal use of this type as an expression	 plate_judge.cpp 

### ISSUE THREAD

**Issue by axia75** [liuruoze/EasyPR#244]
vs2015 libeasypr 编译时候 C2275 'cv::ml::SVM': illegal use of this type as an expression	 plate_judge.cpp 
请问如何解决这个 c2275 问题啊

**Comment by fffmonkeyking** [comment]
modify config.h:

//#define CV_VERSION_THREE_ZERO
#define CV_VERSION_THREE_TWO

to solve it
