### ISSUE TITLE
opencv 3.2   vs2015 配置 easyPR

### ISSUE THREAD

**Issue by Huangzebin99** [liuruoze/EasyPR#245]
各位大牛们，想请教一个问题。
我按照readme中步骤：
1、配置opencv环境；
2、在config.h内添加了#define CV_VERSION_THREE_TWO
选择编译类型为x64编译的时候就会出现：
2>xmlParser.obj : error LNK2019: unresolved external symbol __imp_IsTextUnicode referenced in function "char __cdecl myIsTextWideChar(void const *,int)" (?myIsTextWideChar@@YADPEBXH@Z)

2>xmlParser.obj : error LNK2019: unresolved external symbol __imp_MessageBoxA referenced in function "public: static struct XMLNode __cdecl XMLNode::openFileHelper(char const *,char const *)" (?openFileHelper@XMLNode@@SA?AU1@PEBD0@Z)

想请教一下这个问题是怎么回事？如何解决呢？谢谢

**Comment by carmanlwf** [comment]
lnk错误一般是库的链接问题，你检测一下配置吧，特别是链接库配置的地方

**Comment by John-Chan** [comment]
把项目根目录下的`CMakeLists.txt` 换成[我这个](https://github.com/John-Chan/EasyPR/blob/vs-cmake/CMakeLists.txt)应该就可以了.

使用方法:
https://github.com/John-Chan/EasyPR/blob/vs-cmake/cmake-generator.md

**Comment by Huangzebin99** [comment]
你好，想请问一下在windows下是直接用你提供的CMakeLists.txt替换EasyPR-master目录下的CMakeLists.txt就可以解决这个问题呢？

**Comment by John-Chan** [comment]
@Huangzebin99 是的,你只需要指定OpenCV的路径就行了.只有OpenCV ,EasyPR,VC 三者之间可以兼容,可以支持任何版本的VS

**Comment by Huangzebin99** [comment]
> 你好，我将这个.txt文件替换了thirdparty中的CMakeLists.txt，之后编译时还是出现了一样的错误

**Comment by John-Chan** [comment]
@Huangzebin99 是替换根目录下的CMakeLists.txt

如果你实在是弄不好,试试我的fork https://github.com/John-Chan/EasyPR.git ,我也是vs2015+openCV3.2 应该不会有问题.
**签下来后切换到vs-cmake这个分支**
然后在代码**根目录**执行

```
mkdir _build
cd _build
set OPENCV_INSTALL_DIR=D:\shared\sdk-dir\opencv\3.2.0\build
# 如果你的openCV不是64位的,就把`Win64`去掉
cmake -G "Visual Studio 14 2015 Win64" ..
```
你需要的vs2015 工程文件在 `_build`目录下
