### ISSUE TITLE
汉字识别率低！！！Help

### ISSUE THREAD

**Issue by moonsummer** [liuruoze/EasyPR#248]
** environment:**

* **System:** raspberry ubuntu mate

* **Compiler version/IDE:*gcc4.8

* **CMake version: 3.5.1

* **OpenCV version:3.1 

汉字车牌识别率低，比如京A12345，京字会识别成其他省份。这个怎么解决啊，卡了好长时间！！！

help！

**Comment by dcscodelife** [comment]
京字的识别原理是什么？感觉需要重新生成模型吧，如果是机器学习方法的话

**Comment by shenhf** [comment]
辽B 设备 宁B了
蓝牌:宁BSB888

**Comment by dcscodelife** [comment]
可以替换自己的字库重新训练

**Comment by zhongshun89** [comment]
车牌号码很搞笑~

**Comment by liuruoze** [comment]
汉字识别率低的问题，除非替换ann，否则较难有很好的办法解决。下个版本的主要目的就是改善这个。
