### ISSUE TITLE
v1.2 centos 编译出错，刚下载的

### ISSUE THREAD

**Issue by abanger** [liuruoze/EasyPR#25]
环境：
2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
opencv-2.4.9

[root@v01lab EasyPR-1.2]# make
Scanning dependencies of target EasyPR
[  4%] Building CXX object CMakeFiles/EasyPR.dir/src/main.cpp.o
[  9%] Building CXX object CMakeFiles/EasyPR.dir/src/core/core_func.cpp.o
[ 13%] Building CXX object CMakeFiles/EasyPR.dir/src/core/chars_identify.cpp.o
[ 18%] Building CXX object CMakeFiles/EasyPR.dir/src/core/chars_recognise.cpp.o
/home/pr/EasyPR12/src/core/chars_recognise.cpp: In constructor ‘easypr::CCharsRecognise::CCharsRecognise()’:
/home/pr/EasyPR12/src/core/chars_recognise.cpp:9: error: ‘nullptr’ was not declared in this scope
/home/pr/EasyPR12/src/core/chars_recognise.cpp: In destructor ‘easypr::CCharsRecognise::~CCharsRecognise()’:
/home/pr/EasyPR12/src/core/chars_recognise.cpp:17: error: ‘nullptr’ was not declared in this scope
/home/pr/EasyPR12/src/core/chars_recognise.cpp:21: error: ‘nullptr’ was not declared in this scope
make[2]: *** [CMakeFiles/EasyPR.dir/src/core/chars_recognise.cpp.o] Error 1
make[1]: *** [CMakeFiles/EasyPR.dir/all] Error 2
make: *** [all] Error 2

**Comment by liuruoze** [comment]
@Micooz 请帮忙看下

**Comment by Micooz** [comment]
nullptr是C++11标准的关键字，更新你的编译器再试。

**Comment by abanger** [comment]
@Micooz  
gcc 4.8.2
[root@v01lab EasyPR12]# make 
[  4%] Building CXX object CMakeFiles/EasyPR.dir/src/main.cpp.o
[  9%] Building CXX object CMakeFiles/EasyPR.dir/src/core/core_func.cpp.o
[ 13%] Building CXX object CMakeFiles/EasyPR.dir/src/core/chars_identify.cpp.o
[ 18%] Building CXX object CMakeFiles/EasyPR.dir/src/core/chars_recognise.cpp.o
/home/pr/EasyPR12/src/core/chars_recognise.cpp: In constructor ‘easypr::CCharsRecognise::CCharsRecognise()’:
/home/pr/EasyPR12/src/core/chars_recognise.cpp:11: error: ‘nullptr’ was not declared in this scope
/home/pr/EasyPR12/src/core/chars_recognise.cpp: In destructor ‘easypr::CCharsRecognise::~CCharsRecognise()’:
/home/pr/EasyPR12/src/core/chars_recognise.cpp:21: error: ‘nullptr’ was not declared in this scope
/home/pr/EasyPR12/src/core/chars_recognise.cpp:25: error: ‘nullptr’ was not declared in this scope
make[2]: *** [CMakeFiles/EasyPR.dir/src/core/chars_recognise.cpp.o] Error 1
make[1]: *** [CMakeFiles/EasyPR.dir/all] Error 2
make: *** [all] Error 2
