### ISSUE TITLE
可以添加识别新能源车牌吗？

### ISSUE THREAD

**Issue by bolming** [liuruoze/EasyPR#250]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[x] help wanted
[x] feature request
```

**Current behavior**
不能识别上海新能源车牌绿底黑字的车牌。
![capture](https://user-images.githubusercontent.com/5639040/30732121-92891b42-9fa3-11e7-80c8-c6d97013f1ff.JPG)
![timg 3](https://user-images.githubusercontent.com/5639040/30731914-b1434d4c-9fa2-11e7-97c7-08f2fc1e9655.jpg)

**Expected/desired behavior**
现在新能源车也多起来了， 希望能添加识别新能源车牌。

**Please tell us about your environment:**
* **System:** Android
Android使用的so库，主要参考[EasyPR_Android](https://github.com/linuxxx/EasyPR_Android)修改的。

**Comment by liuruoze** [comment]
新能源车最大的问题不是颜色，而是它是8个字符，这意味着要改变字符分割的架构，同时，车牌判断部分也需要加入对其的支持
