### ISSUE TITLE
macos下使用3.8cmake和3.2opencv用build.sh时出现问题

### ISSUE THREAD

**Issue by CavendishBosh** [liuruoze/EasyPR#251]
[ ] help wanted
yuboxideMacBook-Pro:EasyPR-master  cavendishforscut$ ./build.sh
CMake Warning (dev) at CMakeLists.txt:50:
  Syntax Warning in cmake code at column 32

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:50:
  Syntax Warning in cmake code at column 38

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:51:
  Syntax Warning in cmake code at column 26

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:51:
  Syntax Warning in cmake code at column 30

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:52:
  Syntax Warning in cmake code at column 36

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:52:
  Syntax Warning in cmake code at column 41

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:53:
  Syntax Warning in cmake code at column 26

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:53:
  Syntax Warning in cmake code at column 30

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:64:
  Syntax Warning in cmake code at column 80

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:65:
  Parse error.  Function missing ending ")".  Instead found unterminated
  string with text ")

  ".

-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.

**Comment by liuruoze** [comment]
应该是cmake版本或者是编码的原因

**Comment by liuruoze** [comment]
如果这个问题依然存在，可以open这个issue。
