### ISSUE TITLE
try这张图片

### ISSUE THREAD

**Issue by fffmonkeyking** [liuruoze/EasyPR#252]
![1](https://user-images.githubusercontent.com/25978767/31433508-2c1ac5fa-aeac-11e7-8751-98def30c8bbe.jpg)

川A.M9513
--->
plateRecognize: 蓝牌:辽YAM951

不知道能不能看见附件图片

**Comment by liuruoze** [comment]
左边缘被遮挡了，导致字符分割出现了问题。EasyPR接受的输入最好是一张包括完整车牌的图片。
