### ISSUE TITLE
在运行DEMO.exe时出现异常

### ISSUE THREAD

**Issue by wyd1520** [liuruoze/EasyPR#256]
使用1.6版本 opencv为3.3.0版本 Debug编译通过后，跑起来提示运行 1.测试-->7.plate_recognize（车牌识别），提示下面，另外我使用1.5的懒人包就没这问题，跟踪进去charsSegmentUsingOSTU 报异常，这要怎么解决

Debug Assertion Failed!

Program: E:\EasyPR\EasyPR-1.6\EasyPR-1.6\demo.exe
File: f:\dd\vctools\crt\crtw32\misc\dbgdel.cpp
Line: 52

Expression: _BLOCK_TYPE_IS_VALID(pHead->nBlockUse)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

**Please tell us about your environment:**

* **System:** Win7 x64

* **Compiler version/IDE:** VS2013

* **OpenCV version:** [3.3 ]

**Comment by toasun** [comment]
用3.2跑

**Comment by wyd1520** [comment]
@toasun 谢谢搞定了

**Comment by stq054188** [comment]
@wyd1520请问您如何解决的呢，谢谢，我用了3.2还是不行
