### ISSUE TITLE
关于model文件夹下的svm模型

### ISSUE THREAD

**Issue by Leelaobai** [liuruoze/EasyPR#258]
作者您好。
非常感谢您开放这么好的作品。这里有一个问题。您在model文件夹下提供的svm_hist.xml文件，我注意到它需要352维的输入，但是又看到您源代码中有多钟svm训练方式，请问您这需要352维输入的模型，输入特征具体是哪种情况？或者说，您这352维的输入特征是怎么计算的？因为我尝试自己训练一个简单的svm模型来判别车牌的时候，总是无法收敛，因此想直接拿您训练好的模型来用。谢谢解答

**Comment by liuruoze** [comment]
feature.cpp里有：

void getHistomPlusColoFeatures(const Mat& image, Mat& features) {
  // TODO
  Mat feature1, feature2;
  getHistogramFeatures(image, feature1);
  getColorFeatures(image, feature2);
  hconcat(feature1.reshape(1, 1), feature2.reshape(1, 1), features);
}

**Comment by Leelaobai** [comment]
谢谢，已经在看了。

**Comment by Leelaobai** [comment]
感谢您的回复。我自己试了试，用svm_hist.xml这个模型，我测试的结果是，蓝色车牌和非车牌判断的正确率很高，但是对于黄色的车牌，正确率却非常低。请问，是这个模型本身就是针对蓝色车牌和非车牌的吗？或者说是我的测试有问题。

**Comment by liuruoze** [comment]
不是的。模型应该可以把黄色车牌和蓝色车牌都识别为车牌的。
