### ISSUE TITLE
EasyPR批量测试时打不开定位结果展示窗口

### ISSUE THREAD

**Issue by 787134351** [liuruoze/EasyPR#266]
你好，我是新手，我在accuracy.hpp中修改 pr.setResultShow(false) 为 pr.setResultShow(true)，想让批量测试显示出车牌定位的效果。
如下所示：
      // parameters
      const bool filesNatureSort = true;
      const int max_plates = 4;
      const int isGenerateGT = 1;

      // set the parameters of CPlateRecognize
      CPlateRecognize pr;
      pr.setResultShow(true);
      pr.setLifemode(true);
      pr.setDetectType(PR_DETECT_COLOR | PR_DETECT_CMSER);
      pr.setMaxPlates(4);
但是结果展示窗口还是没打开，其他一切正常。
该怎么解决呢？

**Please tell us about your environment:**

* **System:** ubuntu16.04

* **Compiler version/IDE:** gcc 5.4.0

* **CMake version:** 3.10.1

* **OpenCV version:** [3.2]

**Comment by 787134351** [comment]
已解决，谢谢。

**Comment by ball26810** [comment]
可以方便說明一下如何解決的嗎??  
我的環境也是跟你差不多 
只有 CMAKE是 VERSION 3.5.1 其他環境相同
DEMO的功能都正常可以使用
