### ISSUE TITLE
plate_locate.cpp 运行时错误

### ISSUE THREAD

**Issue by cyniu** [liuruoze/EasyPR#27]
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/opencv-pcqRHK/opencv-2.4.10.1/modules/core/src/matrix.cpp, line 323
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-pcqRHK/opencv-2.4.10.1/modules/core/src/matrix.cpp:323: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

使用如下测试图片
![test](https://cloud.githubusercontent.com/assets/3487944/7135466/9f44e944-e2d9-11e4-90b7-2426772c4297.jpg)

**Comment by liuruoze** [comment]
下一个版本fix会修正这个，先暂时用 批量测试-> native_test来测试这个图片

**Comment by liuruoze** [comment]
已修正

**Comment by immortalnovayang** [comment]
您好，请问一下，目前使用1.3版将image/test.jpg进行3-1产生notlabel数据后，执行选项3-2 的”标签learndata” 也会出现如上的assertion failed信息，关于这个错误，是否会在1.3正式版修正，谢谢!!
