### ISSUE TITLE
VS2017编译时找不到文件

### ISSUE THREAD

**Issue by Catastrophe1** [liuruoze/EasyPR#275]
**编译失败，找不到并无法打开文件** 

```
help wanted
```
<img width="641" alt="default" src="https://user-images.githubusercontent.com/12708640/37253146-99b8bac6-2568-11e8-9d6f-96061f3f02a8.PNG">
项目文件夹内并没有这4个文件，编译无法通过。

* **System:** Windows10

* **Compiler version/IDE:** VS2017

* **OpenCV version:**  3.1

**Comment by velarn** [comment]
~~Demo属性-c/c++/常规/附加包含目录下添加easypr根目录。~~
上面的无效。

**Comment by Catastrophe1** [comment]
试了一下还是这样。。。之前运行的时候已经包含了easypr/include目录了==；我想问一下你项目文件里有这四个cpp文件吗？我没找到。。。我后面把编译文件这四个文件注释掉后，编译还是不通过，好像项目确实依赖这4个文件里的函数的。。。。

**Comment by velarn** [comment]
抱歉，我把.cpp看成.hpp了。我的项目文件里没搜到这四个文件哎。请问你下的是最新版本么？另外环境配置是用python配置的还是手动配置的？我在配置环境的时候是手动配置的。

**Comment by Catastrophe1** [comment]
是python配置的，下的最新版本也是这样的情况==；我看 vxproj里的编译文件里也包含了这四个cpp，把它们注释掉编译还是通不过。。。
还是要谢谢你哈：）

**Comment by Catastrophe1** [comment]
<img width="433" alt="s s s" src="https://user-images.githubusercontent.com/12708640/37342942-10ca04dc-2701-11e8-82b3-2ac1a9aadf9b.PNG">
这是编译文件，把他们注释了还是不行==

**Comment by velarn** [comment]
configure.py不适用于1.6版本的配置了，我刚才试了一下，生成的文件和你的一样，估计是从libeasypr.vcxproj.template文件中复制过来的。所以还是手动配置一下吧。我手动配置的没有问题。

**Comment by Catastrophe1** [comment]
谢谢啦～确实是手动配置的问题：）
