### ISSUE TITLE
你好，请问thirdparty这个是在哪里？

### ISSUE THREAD

**Issue by shadowandfatshadow** [liuruoze/EasyPR#277]
我在编译的时候会出现这些错误
.\src\core\feature.cpp(3): fatal error C1083: 无法打开包括文件: “thirdparty/LBP/lbp.hpp”: No such file or directory
1>  core_func.cpp
1>..\src\core\core_func.cpp(6): fatal error C1083: 无法打开包括文件: “thirdparty/mser/mser2.hpp”: No such file or directory
1>  chars_segment.cpp
1>..\src\core\chars_segment.cpp(6): fatal error C1083: 无法打开包括文件: “thirdparty/mser/mser2.hpp”: No such file or directory
1>  chars_identify.cpp

**Comment by SoarAnyway** [comment]
在"thirdparty/"前面加上"../"就好了
