### ISSUE TITLE
色彩定位光照处理要加强

### ISSUE THREAD

**Issue by leiyu1980** [liuruoze/EasyPR#28]
比如黑E 苏E这种如果原点前两个汉字的地方，光照比较强，色彩判断就会因为字体白色范围比较大造成区域错误

**Comment by liuruoze** [comment]
如果能够提供更进一步的信息的话会更好，例如图片说明之类

**Comment by leiyu1980** [comment]
就是这个图片
![vlcsnap-2015-04-22-14h02m02s148](https://cloud.githubusercontent.com/assets/8098992/7268132/41c7c870-e8f8-11e4-96cf-cc7b4bebd4bf.png)

**Comment by liuruoze** [comment]
OK，你有没有加入讨论群？如果有的话，昵称是什么？

**Comment by leiyu1980** [comment]
我没有加，我找找群号
