### ISSUE TITLE
Out of range comparation has no effect to whiteCount in function "clearLiuDingOnly"

### ISSUE THREAD

**Issue by Micooz** [liuruoze/EasyPR#29]
core_func.cpp 373:
```cpp
if (img.at<char>(i, j) == 255)
{
	whiteCount++;
}
```
Comparison of constant 255 with expression of type 'char' is always false, so whiteCount is always zero.

**Comment by liuruoze** [comment]
I am not very sure, but I will take an experiment

**Comment by liuruoze** [comment]
刚才的测试结果是是可以给char赋数值常量，但是跟255的比较会返回false

```cpp
#include <iostream>
using namespace std;

int main()
{
	char a = 255;
	cout << a << endl;
	cout << (a == 255) << endl;

	cin >> a;

	return 0;
}
```
![image 1](https://cloud.githubusercontent.com/assets/8255297/7271221/8e70a630-e914-11e4-9cc8-8aeccd86c618.png)

相反，如果把char改成 unsigned char，以后
```cpp
#include <iostream>
using namespace std;

int main()
{
	unsigned char a = 255;
	cout << a << endl;
	cout << (a == 255) << endl;

	cin >> a;

	return 0;
}
```
结果则是：
![image 2](https://cloud.githubusercontent.com/assets/8255297/7271321/21ed8e5a-e915-11e4-81ff-e77c9ea41c75.png)

因此，建议把这句改为
```cpp
if (img.at<uchar>(i, j) == 255)
{
	whiteCount++;
}
```

**Comment by liuruoze** [comment]
已修复
