### ISSUE TITLE
EasyPR failed to build "main.obj : error LNK2019: unresolved external symbol "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z) referenced in function "class cv::Mat __cdecl cv::imread$exit_thunk(class cv::String const &,int)" (?imread$exit_thunk@cv@@$$hYA?AVMat@1@AEBVString@1@H@Z) (EC Symbol)" with MSVC on Windows arm64ec.

### ISSUE THREAD

**Issue by YangYang129** [liuruoze/EasyPR#327]
`EasyPR failed to build "main.obj : error LNK2019: unresolved external symbol "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z) referenced in function "class cv::Mat __cdecl cv::imread$exit_thunk(class cv::String const &,int)" (?imread$exit_thunk@cv@@$$hYA?AVMat@1@AEBVString@1@H@Z) (EC Symbol)" with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?`
**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/liuruoze/EasyPR F:\gitP\liuruoze\EasyPR
3. git -C "F:\gitP\liuruoze\EasyPR" apply f:\agent\_work\9\s\src\qa\suites\oss\patch\easypr\easypr_change_cmakelists.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
4. git -C "F:\gitP\liuruoze\EasyPR" apply f:\agent\_work\9\s\src\qa\suites\oss\patch\easypr\easypr_change_configfile.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
5. cd F:\gitP\Microsoft\vcpkg
6. bootstrap-vcpkg.bat 2>&1
7. vcpkg.exe install --recurse opencv3 --triplet arm64-windows --clean-after-build 2>&1
8. cd F:\gitP\liuruoze\EasyPR\build_arm64ec
9. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows .. 2>&1
10. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release easypr.sln /t:Rebuild 2>&1

**Error info:**
```
8>main.obj : error LNK2019: unresolved external symbol "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z) referenced in function "class cv::Mat __cdecl cv::imread$exit_thunk(class cv::String const &,int)" (?imread$exit_thunk@cv@@$$hYA?AVMat@1@AEBVString@1@H@Z) (EC Symbol) [F:\gitP\liuruoze\EasyPR\build_arm64ec\demo.vcxproj]
     8>easypr.lib(svm_train.obj) : error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z) (EC Symbol) [F:\gitP\liuruoze\EasyPR\build_arm64ec\demo.vcxproj]
     8>easypr.lib(ann_train.obj) : error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z) (EC Symbol) [F:\gitP\liuruoze\EasyPR\build_arm64ec\demo.vcxproj]
     8>easypr.lib(annCh_train.obj) : error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z) (EC Symbol) [F:\gitP\liuruoze\EasyPR\build_arm64ec\demo.vcxproj]
```
**Error log:**
[EasyPR_build_error.log](https://github.com/liuruoze/EasyPR/files/9217198/EasyPR_build_error.log)

Patch log:
[easypr_change_cmakelists.log](https://github.com/liuruoze/EasyPR/files/9217222/easypr_change_cmakelists.log)
[easypr_change_configfile.log](https://github.com/liuruoze/EasyPR/files/9217223/easypr_change_configfile.log)

**Comment by Eric3495** [comment]
邮件发到~~

**Comment by Eric3495** [comment]
邮件发到~~
