### ISSUE TITLE
Assertion failed Issues about cv::Mat

### ISSUE THREAD

**Issue by immortalnovayang** [liuruoze/EasyPR#34]
![error1](https://cloud.githubusercontent.com/assets/11418440/7440865/b5cae374-f0ff-11e4-82ea-f2db37828c58.png)
您好，请问一下，目前使用1.3版将image/test.jpg进行3-1产生notlabel数据后，执行选项3-2 的”标签learndata” 会出现如上的Assertion failed信息，关于这个错误，是否会在1.3正式版修正，谢谢!!

**Comment by liuruoze** [comment]
嗯，会修正的

**Comment by cyniu** [comment]
test_plate_locate
![test](https://cloud.githubusercontent.com/assets/3487944/7722780/f687acde-ff15-11e4-89e9-bf480556b887.jpg)
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/opencv-pcqRHK/opencv-2.4.10.1/modules/core/src/matrix.cpp, line 323

**Comment by liuruoze** [comment]
此问题已解决， @immortalnovayang , @cyniu
