### ISSUE TITLE
linux编译出错

### ISSUE THREAD

**Issue by gjhkael** [liuruoze/EasyPR#35]
CMakeFiles/EasyPR.dir/src/util/generate_gdts.cpp.o: In function `generate_gdts()':
generate_gdts.cpp:(.text+0x17): undefined reference to `cv::CascadeClassifier::CascadeClassifier()'
generate_gdts.cpp:(.text+0x190): undefined reference to `cv::imread(std::string const&, int)'
generate_gdts.cpp:(.text+0x330): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
generate_gdts.cpp:(.text+0x369): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
generate_gdts.cpp:(.text+0x43b): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
generate_gdts.cpp:(.text+0x590): undefined reference to `cv::CascadeClassifier::~CascadeClassifier()'
CMakeFiles/EasyPR.dir/src/util/learn_prepare.cpp.o: In function `label_data()':
learn_prepare.cpp:(.text+0x21c): undefined reference to `cv::imread(std::string const&, int)'
learn_prepare.cpp:(.text+0x3b4): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
都是一些这种类似的问题

**Comment by Micooz** [comment]
请确保你的opencv库安装正确。

**Comment by gjhkael** [comment]
opencv安转的是2.4.10.并且可以确定，安转正确，其他算法都可以编译执行。

**Comment by liuruoze** [comment]
@gjhkael  请用最新版的再试一下，如果还有问题，请再回复一下。
