### ISSUE TITLE
opencv 3.0 没有opencv2\legacy和opencv2/nonfree/

### ISSUE THREAD

**Issue by berli** [liuruoze/EasyPR#36]
opencv3.0没有这两个模块，请fix头文件问题；
否则，无法编译通过
EasyPR/src/include/prep.h:7:42: fatal error: opencv2/nonfree/features2d.hpp: No such file or directory

**Comment by vrqin** [comment]
OpenCV 3.0对模块的封装都做了调整, 不单是修改头文件能解决的
单我看到就有ML模块的变化, 需要重新修改对SVM和神经网络的使用
