### ISSUE TITLE
在进行调试，连续选择3 ，会中断，具体原因不详。

### ISSUE THREAD

**Issue by wanghou** [liuruoze/EasyPR#38]
在进行调试，连续选择3 ，会中断，具体原因不详。

**Comment by liuruoze** [comment]
可以贴图的，把图贴上来效果更好。
而且描述也要更仔细一点。

**Comment by wanghou** [comment]
在进调试时 ，如果进入3，则会出现中断，具体原因不详，如图所示：


![Uploading bugpic1.png…]()
![Uploading bugpic.jpg…]()

**Comment by liuruoze** [comment]
@wanghou 这个问题无法重现
