### ISSUE TITLE
mac 遇到错误 EasyPR/include/easypr/util.h:74:42: error: no type named 'initializer_list' in namespace 'std'   static void print_str_lines(const std::initializer_list<const char*>& lines) {

### ISSUE THREAD

**Issue by rattlebush1226** [liuruoze/EasyPR#40]
cmake . 之后，运行make 时遇到了下面的错误：
$ make
[  5%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_segment.cpp.o
In file included from ~/EasyPR/src/core/chars_segment.cpp:2:
~/EasyPR/include/easypr/util.h:74:42: error: no type named 'initializer_list' in namespace 'std'
  static void print_str_lines(const std::initializer_list<const char*>& lines) {
                                    ~~~~~^
~/EasyPR/include/easypr/util.h:74:58: error: expected ')'
  static void print_str_lines(const std::initializer_list<const char*>& lines) {
                                                         ^
~/EasyPR/include/easypr/util.h:74:30: note: to match this '('
  static void print_str_lines(const std::initializer_list<const char*>& lines) {
                             ^
~/EasyPR/include/easypr/util.h:75:22: error: use of undeclared identifier 'lines'; did you mean 'line'?
    for (auto line : lines) {
                     ^~~~~
                     line
/usr/local/include/opencv2/core/core.hpp:2613:19: note: 'line' declared here
CV_EXPORTS_W void line(CV_IN_OUT Mat& img, Point pt1, Point pt2, const Scalar& color,
                  ^
In file included from ~/EasyPR/src/core/chars_segment.cpp:2:
~/EasyPR/include/easypr/util.h:75:20: error: invalid range expression of type
      'void (cv::Mat &, cv::Point_<int>, cv::Point_<int>, const cv::Scalar_<double> &, int, int, int)'; no viable 'begin' function available
    for (auto line : lines) {


不知道您在做mac os 移植的时候是怎样解决的。 我的Mac 版本是 10.10.2

谢谢！

**Comment by Micooz** [comment]
尝试给include/easypr/util.h 添加 #include <initializer_list> 来解决这个问题。

**Comment by rattlebush1226** [comment]
添加 #include <initializer_list>之后，出现下面的错误

EasyPR/include/easypr/util.h:7:10: fatal error: 'initializer_list' file not found
#include <initializer_list>

我查过一些资料，
http://stackoverflow.com/questions/10991274/initializer-list-in-clang

貌似是因为 Clang 默认是98模式，但是 initializer_list 是c++11的特性， 我的clang 版本是：
$ clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

抱歉，我c++不是很熟，不知道你有没有遇到这个问题。

谢谢~

**Comment by Micooz** [comment]
你的Clang应该是支持c++11的，可能是Clang不认识定义在CMakeLists中的-std=c++11选项，将其改为-std=c++0x或许可以解决你的问题。

**Comment by rattlebush1226** [comment]
我把CMakeLists 改成这样

# c++11 required
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++ -std=c++0x")

之后，make, 解决了之前的错误，但是遇到了新的问题，
81 warnings generated.
Linking CXX executable easypr_test
Undefined symbols for architecture x86_64:
  "CvSVMParams::CvSVMParams()", referenced from:
      easypr::Svm::train(bool, float, bool, char const*) in libeasypr.a(svm_train.cpp.o)
  "cv::FileStorage::FileStorage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      easypr::Svm::train(bool, float, bool, char const*) in libeasypr.a(svm_train.cpp.o)
  "cv::_InputArray::_InputArray(cv::Mat const&)", referenced from:
      easypr::demo::test_chars_segment() in main.cpp.o
      easypr::demo::test_plate_locate() in main.cpp.o
      easypr::demo::test_plate_judge() in main.cpp.o
      easypr::demo::test_plate_detect() in main.cpp.o
      easypr::CPlateJudge::histeq(cv::Mat) in libeasypr.a(plate_judge.cpp.o)
      easypr::CPlateJudge::plateJudge(std::__1::vector<easypr::CPlate, std::__1::allocator<easypr::CPlate> > const&, std::__1::vector<easypr::CPlate, std::__1::allocator<easypr::CPlate> >&) in libeasypr.a(plate_judge.cpp.o)
      easypr::CPlateDetect::showResult(cv::Mat const&) in libeasypr.a(plate_detect.cpp.o)
      ...

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [easypr_test] Error 1
make[1]: *** [CMakeFiles/easypr_test.dir/all] Error 2
make: *** [all] Error 2

在网上找了些答案， http://stackoverflow.com/questions/19821041/g-ld-symbols-not-found-for-architecture-x86-64，
On 10.8 and earlier libstdc++ is chosen by default, on 10.9 libc++ is chosen by default. To ensure compatibility with libMLi3, we need to choose libstdc++ manually.

To do this, add -stdlib=libstdc++

但我改成 -stdlib=libstdc++ 之后，又会遇到 之前的 “ error: no type named 'initializer_list' in namespace 'std' ” 问题。

另外，我把您的改动pull 下来之后，还是无法解决  error: no type named 'initializer_list' in namespace 'std'  问题。
