### ISSUE TITLE
svm_train bug

### ISSUE THREAD

**Issue by colinback** [liuruoze/EasyPR#41]
我在windows测试SVM train的时候遇到一个问题。
文件名是plate_344.jpg，但是sprintf之后save_to就不对了，我改成如下就过了：
sprintf(save_to, "%s/train/%s", images_folder, file_name.c_str());

PS: 目前divide必须手动添加目录/has/train, /has/test, /no/train/, /no/test；为啥不检验一下目录是否存在，然后自动添加呢？比如在UTIL里添加：

bool Util::testIfFolderExist(const string &folder) {
#if defined(WIN32) || defined(_WIN32)
	if (_access(folder.c_str(), 0) == 0)
		return true;
	else {
		string command = "mkdir " + folder;
		system(command.c_str());
		return true;
	}
#elif defined(linux) || defined(__linux__) || defined(__APPLE__)
	DIR *dp;
	if ((dp = opendir(path)) == NULL) {
		string command = "mkdir -p " + folder;
		system(command.c_str());
		return true;
	}
	else
		return true;
#endif
	return false;
}

**Comment by colinback** [comment]
![bug](https://cloud.githubusercontent.com/assets/2142335/8155105/711ac87a-1373-11e5-9802-4728fca8e05a.jpg)

**Comment by Micooz** [comment]
utils::imwrite会自动创建目录，不用手动添加。没能理解为什么你sprintf后save_to为什么不对，请贴一下f变量的值。

**Comment by colinback** [comment]
图片是随机的，这次选了另外一幅

![debug1](https://cloud.githubusercontent.com/assets/2142335/8179340/967d8528-1448-11e5-9063-7a36b359570a.jpg)

**Comment by colinback** [comment]
![Uploading debug2.jpg…]()

**Comment by colinback** [comment]
如果按照前面添加c_str()编译，然后运行命令如下：
![debug2](https://cloud.githubusercontent.com/assets/2142335/8179651/9f36b764-144a-11e5-95ed-65cd7847f459.jpg)

**Comment by colinback** [comment]
感觉走了utils:imwrite的，但是has目录下没有train目录
![debug3](https://cloud.githubusercontent.com/assets/2142335/8179671/c0595294-144a-11e5-877a-784abde06a34.jpg)

**Comment by colinback** [comment]
好像是windows和linux系统目录差别的问题...这样就ok了
sprintf(save_to, "%s\\train\\%s", images_folder, file_name.c_str());

**Comment by colinback** [comment]
sprintf(save_to, "%s\\\train\\\%s", images_folder, file_name.c_str());
