### ISSUE TITLE
源代码编码支持UTF8，easypr_test界面支持UTF8

### ISSUE THREAD

**Issue by fabware** [liuruoze/EasyPR#43]
车牌识别感觉就这个项目很靠谱，下载了一个到mac下试了一下。源代码注释都是乱码，easypr_test的输出都是乱码（连输出的车牌号都是乱码）。

不知道是我哪个地方设置不正确，还是真有问题。希望能改进一下，方便linux平台的开发和调试。

**Comment by Micooz** [comment]
为了配合VisualStudio，目前代码文件是GBK编码，你的编辑器设定编码非GBK或者GB2312，因此注释出现乱码。
*unix的bash默认编码是UTF8，因此输出出现乱码。

在 https://github.com/Micooz/EasyPR/tree/master 可以获得UTF8版本。
