### ISSUE TITLE
极端情况下车牌识别

### ISSUE THREAD

**Issue by maxwellxxx** [liuruoze/EasyPR#44]
作者您好，我想问下源码中提供的extreme_test，目前我实验时结果都是“无车牌”，是暂时不能识别，还是我个人的问题？

**Comment by liuruoze** [comment]
extreme_test的图片属于待攻克的问题，目前仅仅是提供给使用者参考研究用。这里的图片会随着EasyPR版本不断的提升而攻克，攻克以后，这些图片也许会转移到general_test下面。

**Comment by maxwellxxx** [comment]
好的，谢谢。那我研究研究。。。。
