### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by kassol** [liuruoze/EasyPR#45]
平台：OS X 10.10.4

OpenCV 版本：2.4.11

运行命令：./easypr_test recognize -p ../resources/image/plate_recognize.jpg --svm ../resources/model/svm.xml -ann ../resources/model/ann.xml

目录结构：以上命令路径没错

错误信息：OpenCV Error: Assertion failed (layer_sizes != 0) in predict, file /tmp/opencv20150611-92017-pixpdt/opencv-2.4.11/modules/ml/src/ann_mlp.cpp, line 1611
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv20150611-92017-pixpdt/opencv-2.4.11/modules/ml/src/ann_mlp.cpp:1611: error: (-215) layer_sizes != 0 in function predict

**Comment by Micooz** [comment]
**--ann** not **-ann**  :)

**Comment by kassol** [comment]
Sorry~我的错，不过文件编码好像有问题，git clone 下来的代码编译之后输出的结果中文全部乱码，然后几个源码直接用Sublime打开中文也是乱码~
