### ISSUE TITLE
训练生成的svm.xml应该怎么用？

### ISSUE THREAD

**Issue by kassol** [liuruoze/EasyPR#46]
根据文档
![2015-07-08 11 33 27](https://cloud.githubusercontent.com/assets/2148666/8562485/401288cc-2565-11e5-8adc-48d085b08cd5.png)
生成的训练结果，我把他替换到了resources/model里面，然后再测试的时候提示出错，请问我是哪里有问题吗？

错误信息：
OpenCV Error: Sizes of input arguments do not match (The sample size is different from what has been used for training) in cvPreparePredictData, file /tmp/opencv20150611-92017-pixpdt/opencv-2.4.11/modules/ml/src/inner_functions.cpp, line 1114
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv20150611-92017-pixpdt/opencv-2.4.11/modules/ml/src/inner_functions.cpp:1114: error: (-209) The sample size is different from what has been used for training in function cvPreparePredictData

**Comment by Zhouguoduan** [comment]
就是说你测试样本的大小跟训练样本的大小不一致，当然不能测试，你需要改一下代码，就是把测试样本大小resize之后，再进行测试。
