### ISSUE TITLE
发现两个BUG，CCharsRecognise和CPlateDetect这两个类中的指针类型成员变量new之后未做delete，有内存泄露

### ISSUE THREAD

**Issue by zydream** [liuruoze/EasyPR#47]
发现两个BUG，CCharsRecognise和CPlateDetect这两个类中的指针类型成员变量new之后未做delete，有内存泄露

**Comment by Micooz** [comment]
并未为CCharsRecognise和CPlateDetect动态分配内存，但确实存在如下内存泄露：

**plate_detect.cpp**:

    11 m_plateLocate = new CPlateLocate();
    12 m_plateJudge = new CPlateJudge();

**chars_recognise.cpp**:

    10 m_charsSegment = new CCharsSegment();
    11 m_charsIdentify = new CCharsIdentify();
