### ISSUE TITLE
高分辨率图片的识别

### ISSUE THREAD

**Issue by Burningbook** [liuruoze/EasyPR#49]
识别太高分辨率图片时会出现问题，将原图片按比例缩小成600X800左右可以正常识别。这个可以在识别前加一个对图片大小的归一化来实现吧

**Comment by Burningbook** [comment]
我是说加一个对图片大小的归一化来修正- -

**Comment by szad670401** [comment]
尺度空间问题。

**Comment by albin3** [comment]
直接归一化尺寸会导致大图片的质量下降。
如果车牌在图片中占有的空间比例很小的情况会有问题吧？

**Comment by szad670401** [comment]
尺度空间不同在做形态学操作的时候也会不同。
比如说太大的车牌，垂直边缘太过离散，导致检测不出来。

**Comment by HenuFSH** [comment]
cvtColor(src, src_hsv, CV_BGR2HSV); 这个转换总是抛出异常，应该怎么处理？

**Comment by GodBlessZhk** [comment]
@HenuFSH 是不是没有进行归一化

新人，回答不好请见谅~

**Comment by HenuFSH** [comment]
@GodBlessZhk 进行归一化了，还是不行。
