### ISSUE TITLE
如何自己训练 SVM 模型呢？

### ISSUE THREAD

**Issue by Zhouguoduan** [liuruoze/EasyPR#51]
我看了开发教程，也看了程序，还是没搞清楚我该怎么自己训练 SVM 模型。 请楼主点拨一下好吗？谢谢！

**Comment by Zhouguoduan** [comment]
好纠结，我使用的是2015年7月12日的版本。Svm::Svm(const char* forward_data_folder, const char* inverse_data_folder): forward_(forward_data_folder), inverse_(inverse_data_folder)。 我不知道forward_data_folder默认代表什么目录，而且auto folder = std::string(forward_).append("/train");和folder = std::string(inverse_).append("/train");分别又是什么意思呢？ 可否把数据的默认目录在一个txt文档中，给我们详细说明一下呢？
       我看到 svm_train.cpp 中没有使用直方图特征，而是把直方图均衡化之后的整幅图片的像素拉成向量，作为训练 svm 模型的特征数据。 这在《EasyPR开发详解》中没有谈到这种特征。 请问，这种特征比直方图特征更好吧？

**Comment by liuruoze** [comment]
一个一个问题来吧，现在最不清楚的地方是哪呢？  PS：如果对SVM不清楚，最好先去学习一下。

**Comment by Zhouguoduan** [comment]
前辈：

谢谢您！这么快就答复我。我是图像处理专业的学生，被延期了，马上就要提交论文了，想自己训练SVM模型。我学过SVM，了解它的基本原理。

我有几处疑问，劳烦您帮我解答一下好吗？期待着你的答复，谢谢！我的问题也许很小白，见笑了。

问题1：我想用你的data来分组、训练、测试，看了教程中“如果你的数据还没分组，那么你执行 3 以后，系统自动帮你分组，然后训练，再测试验证。”，应该选择第3项，也就是“3. 车牌检测(not divide and train);”——会执行svm.train(false, false);  但是我这个地方（如下图）没看明白我看了函数的实现中if语句的条件，觉得应当是svm.train(true, true); 你帮我解释一下行吗？

问题2：你的学习数据已经是打好标签的，训练和测试数据也建好文件夹了。因为train_svm.cpp中有这个函数Svm::Svm(const char* forward_data_folder, const char* inverse_data_folder): forward_(forward_data_folder), inverse_(inverse_data_folder) {assert(forward_); assert(inverse_);}，所以我在main.cpp的函数svmMain()中加了几句代码：

char * forward_data_folder = "positive";

                                                char * inverse_data_folder = "negative";

                                                Svm svm(forward_data_folder, inverse_data_folder);   但是我不知“positive”和“negative”应该写成什么。

        问题3：你是否是把直方图均衡化之后的整幅图片的像素拉成向量，作为训练 svm 模型的输入数据呢？然后用高斯核，映射的向量的维数就是训练数据的总个数吧。我想做个对比试验，也就是使用相同的输入数据，用线性核也训练一下，你看可行吗？

         期待着您的答复，万分感谢！

 

——一个即将毕业的学生  小周

发件人: liuruoze [mailto:notifications@github.com] 
发送时间: 2015年7月20日 14:08
收件人: liuruoze/EasyPR
抄送: Zhouguoduan
主题: Re: [EasyPR] 如何自己训练 SVM 模型呢？ (#51)

 

一个一个问题来吧，现在最不清楚的地方是哪呢？ PS：如果对SVM不清楚，最好先去学习一下。

**Comment by liuruoze** [comment]
一. 在1.3版 @Micooz 对SVM train这部分做了优化，因此跟我开发教程那里的有所不同了。例如这部分应该是都填true，以他的为准吧。

二. 这两个地方就填你分别放有车牌和无车牌的文件夹的名字即可。如果你用我们提供的文件夹的话，默认应该是:hasplate和noplate

三. 这个问题恕我不能帮你，既然你在准备论文，应该自己去尝试。不要害怕弄坏EasyPR，如果你尝试失败了，随时可以选择复原。

**Comment by Zhouguoduan** [comment]
真的是太感谢您了！您给了我莫大的帮助，我赶紧试一试。

如果还有什么问题，也许还得麻烦您呢，还希望您抽出宝贵的时间，解小弟的燃眉之急。

 

发件人: liuruoze [mailto:notifications@github.com] 
发送时间: 2015年7月20日 20:14
收件人: liuruoze/EasyPR
抄送: Zhouguoduan
主题: Re: [EasyPR] 如何自己训练 SVM 模型呢？ (#51)

 

一. 在1.3版 @Micooz <https://github.com/Micooz>  对SVM train这部分做了优化，因此跟我开发教程那里的有所不同了。例如这部分应该是都填true，以他的为准吧。

二. 这两个地方就填你分别放有车牌和无车牌的文件夹的名字即可。如果你用我们提供的文件夹的话，默认应该是:hasplate和noplate

三. 这个问题恕我不能帮你，既然你在准备论文，应该自己去尝试。不要害怕弄坏EasyPR，如果你尝试失败了，随时可以选择复原。
