### ISSUE TITLE
用cmake编译时出现如下错误

### ISSUE THREAD

**Issue by lpx1233** [liuruoze/EasyPR#54]
/home/root/EasyPR-master/src/core/core_func.cpp: In function 'cv::Mat easypr::colorMatch(const cv::Mat&, cv::Mat&, easypr::Color, bool)':
/home/root/EasyPR-master/src/core/core_func.cpp:45:3: error: 'vector' was not declared in this scope
   vector<Mat> hsvSplit;
   ^

我的g++版本是4.9.1,还有很多错误,不好复制过来,似乎大意是找不到vector这个类,需要使用std::vector
求问如何解决?

**Comment by liuruoze** [comment]
可能是 c++ 11特性的问题，具体可以咨询下 @Micooz

**Comment by Micooz** [comment]
测试时未见此类错误，请加上std::前缀来解决问题。

**Comment by lpx1233** [comment]
好的，谢谢你们~ @liuruoze  @Micooz
