### ISSUE TITLE
运行“测试-车牌检测”时，程序出错

### ISSUE THREAD

**Issue by Zhouguoduan** [liuruoze/EasyPR#55]
我是用的Windows版本。
在测试（testMain();）中，最新版本的车牌检测的主要函数是int result = pd.plateDetect(src, resultVec);，可是这个函数会出错。老版本的函数是int result = pd.plateDetectDeep(src, resultVec);，不会出错。不知其他人遇到这个问题没。

**Comment by Zhouguoduan** [comment]
![Uploading 车牌检测单幅图片测试出错.jpg…]()
这究竟问题出在哪里呢？ 在对黄色进行colorSearch()，返回后出错。

**Comment by liuruoze** [comment]
新版本的函数貌似没有这些问题呢，如果还有，请开一个新帖讨论。
