### ISSUE TITLE
怎样对“鲁”进行重新训练？

### ISSUE THREAD

**Issue by bingshuizhang** [liuruoze/EasyPR#56]
使用1.3版本对RTSP流截图识别，对“鲁”字识别非常差，

应该怎样训练?

应该准备多少个样本比较好！

谢谢！

**Comment by liuruoze** [comment]
建议提供一些“鲁”的车牌图片放入EasyPR数据集里，在下一个版本会强化ANN识别率这部分。

**Comment by bingshuizhang** [comment]
对“鲁”字的尺寸有什么要求吗？

**Comment by liuruoze** [comment]
我的意思是贡献一些车牌图片出来，包含鲁字的车牌。
可以选择上传到讨论群里，或者直接发送给管理团队。

**Comment by bingshuizhang** [comment]
这个没有问题，大概需要多少照片，什么场景，目前我们有卡口、电警的照片，还有手机拍照的照片，还有车载拍照的照片，每类需要多少张？
