### ISSUE TITLE
乱码啊，Ubuntu 14.04，如图

### ISSUE THREAD

**Issue by sunlin7** [liuruoze/EasyPR#57]
hi, 
我刚下载编译了，运行起来是乱码啊，是不是编译用utf8编译比较好一点呢？
![Image of Snapshot](http://a2.qpic.cn/psb?/V14OzBJM0ehciT/f7jOq73wIML*nKREPDGkSP8k9WSh*BmN5YOXurI6bac!/b/dCgAAAAAAAAA&bo=0gLOAQAAAAADBz0!&rf=viewer_4)
多谢～

**Comment by liuruoze** [comment]
改一下 shell 窗口的编码到 gbk即可

**Comment by sunlin7** [comment]
果然可以，感谢~

**Comment by AlexHu123** [comment]
你好，我改到了gdk，识别的结果汉字显示是正常的，但是读取的文件名的汉字是乱码？求大大们解答
