### ISSUE TITLE
train报错-easypr_test.exe svm --train --has-plate=has/ --no-plate=no/ --divide --svm=mo del/svm.xml

### ISSUE THREAD

**Issue by jpzhang1230** [liuruoze/EasyPR#58]
Dividing data to be trained and tested...
has/京CX8888_0.jpg -> has//train/京CX8888_0.jpg
has/赣A82F36_12.jpg -> has//train/赣A82F36_12.jpg
has/京A88731_0.jpg -> has//train/京A88731_0.jpg
has/京A88731_2.jpg -> has//train/京A88731_2.jpg
has/京CX8888_1.jpg -> has//test/京CX8888_1.jpg
has/京H99999_0.jpg -> has//test/京H99999_0.jpg
no/赣A82F36_5.jpg -> no//train/赣A82F36_5.jpg
no/赣A82F36_0.jpg -> no//train/赣A82F36_0.jpg
no/京A88731_1.jpg -> no//train/京A88731_1.jpg
no/京H99999_4.jpg -> no//train/京H99999_4.jpg
no/赣A82F36_10.jpg -> no//train/赣A82F36_10.jpg
no/京H99999_3.jpg -> no//train/京H99999_3.jpg
no/赣A82F36_8.jpg -> no//train/赣A82F36_8.jpg
no/赣A82F36_6.jpg -> no//train/赣A82F36_6.jpg
no/京CX8888_2.jpg -> no//train/京CX8888_2.jpg
no/京H99999_2.jpg -> no//train/京H99999_2.jpg
no/京H99999_1.jpg -> no//train/京H99999_1.jpg
no/京H99999_5.jpg -> no//train/京H99999_5.jpg
no/京A88731_4.jpg -> no//train/京A88731_4.jpg
no/赣A82F36_11.jpg -> no//train/赣A82F36_11.jpg
no/赣A82F36_9.jpg -> no//train/赣A82F36_9.jpg
no/赣A82F36_13.jpg -> no//test/赣A82F36_13.jpg
no/赣A82F36_1.jpg -> no//test/赣A82F36_1.jpg
no/赣A82F36_3.jpg -> no//test/赣A82F36_3.jpg
no/赣A82F36_7.jpg -> no//test/赣A82F36_7.jpg
no/赣A82F36_2.jpg -> no//test/赣A82F36_2.jpg
no/赣A82F36_4.jpg -> no//test/赣A82F36_4.jpg
no/京A88731_3.jpg -> no//test/京A88731_3.jpg
Collecting train data...
Collecting train data in has//train
Collecting train data in no//train
Generating svm model file, please wait...
OpenCV Error: Bad argument (While cross-validation one or more of the classes ha
ve been fell out of the sample. Try to enlarge <CvSVMParams::k_fold>) in CvSVM::
do_train, file C:\builds\2_4_PackSlave-win32-vc12-shared\opencv\modules\ml\src\s
vm.cpp, line 1402
C:\builds\2_4_PackSlave-win32-vc12-shared\opencv\modules\ml\src\svm.cpp:1402: er
ror: (-5) While cross-validation one or more of the classes have been fell out o
f the sample. Try to enlarge <CvSVMParams::k_fold> in function CvSVM::do_train

OpenCV Error: Null pointer (Invalid pointer to file storage) in cvStartWriteStru
ct, file C:\builds\2_4_PackSlave-win32-vc12-shared\opencv\modules\core\src\persi
stence.cpp, line 2948

**Comment by jpzhang1230** [comment]
Please take any time to response this issue,thank you very much.why report error when training with the method written in paper?

**Comment by jpzhang1230** [comment]
I find it..svn_train.cpp at line 184 utils::mkdir(out_svm_path);生成的是目录，这样写文件时为null

**Comment by Micooz** [comment]
也许是你没有正确传入out_svm_path参数，utils::mkdir(out_svm_path)是为了保证目标目录存在性，和写文件无关。

**Comment by jpzhang1230** [comment]
保证目录存在性这没有问题，但是后面的svm.write应该指向的是文件，而不是目录，否则文件写的时候会报空指针异常。。我本机修改如下：
 utils::mkdir(out_svm_path);
	  string svmFileName(out_svm_path);
	  svmFileName.append("svm.xml");
	  cv::FileStorage fsTo(svmFileName, cv::FileStorage::WRITE);
	  std::cout << svmFileName << std::endl;
      svm.write(*fsTo, "svm");
也就是说out_svm_path只传一个目录，形如model/,保存的文件在model/svm.xml

**Comment by Micooz** [comment]
原代码没有问题，请仔细检查你的命令行：

    easypr_test.exe svm --train --has-plate=has/ --no-plate=no/ --divide --svm=mo del/svm.xml

你为--svm传入的是mo而不是model/svm.xml，因此写文件会报错。

**Comment by jpzhang1230** [comment]
Thank you for your prompt reply.
