### ISSUE TITLE
关于最新版的一个错误

### ISSUE THREAD

**Issue by wrestle** [liuruoze/EasyPR#59]
不知道有没有被提交过: 在做3.0移植的时候，偶然发现chars_recognise.h中的 CCharsRecognise::charsRecognise的两个参数的重载函数版本声明与实现不符合。
根据声明使用的是cv::String& 实现使用的是std::string&
估计是使用了using语法结果忘记大写了吧？

**Comment by wrestle** [comment]
错误2:
plate_judge.h与plate_judge.cpp中的 
CPlateJudge::plateJudeg实现与声明不符。

**Comment by micooz** [comment]
第一个问题确实存在将被修复，但第二个错误似乎不存在

**Comment by wrestle** [comment]
是我看错了？当时我看到的是
.h里的 int 参数是 引用
.cpp里的 则是 int
如果没有那也许是我不小心摁上去的。
