### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by Brightzh** [liuruoze/EasyPR#61]
我的使用环境是Windows7+VS2013+OpenCV2.4.10，编译没有出什么麻烦，不过在/bin/release下找到easypr_test.exe和libeasypr.lib后，双击运行easypr_test.exe没有出现什么问题，但是不管是哪条指令输入，都是输入错误，找不到文件或者总计图片0张，不知道是什么问题，还请各位大大给点建议。（为了保险，我把OpenCV的dll基本都放在了该程序目录下）

**Comment by micooz** [comment]
也许把可执行程序放在项目根目录下可以解决你的问题。

**Comment by Brightzh** [comment]
我试过这么做，也试过把resources放到release文件夹里，都不行。

**Comment by Brightzh** [comment]
svm显示输入错误，批量测试显示总图片0张。

**Comment by liuruoze** [comment]
直接在vs2013里运行试试呢？
这个问题基本上一般是由于文件路径不对造成的。
由于EasyPR里面的文件都使用的是相对路径，因此试试在开发工具里运行试试看。
