### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [liuruoze/EasyPR#63]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [SAFE_RELEASE](https://github.com/liuruoze/EasyPR/blob/3bdfd8203d4deb61db90b677245845d89a3480ce/include/easypr/util.h#L17 "SAFE_RELEASE macro")
* [Generator](https://github.com/liuruoze/EasyPR/blob/5870dcc924cab2f4d30b89a8a8b93e24d84038d3/src/util/program_options.cpp#L26 "Destructor for Generator")

**Comment by micooz** [comment]
Thx for your precious suggestion, we will fix it soon. Your pullrequests are also appreciated.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/liuruoze/EasyPR/blob/32b0560872f789840012bc06ca505ce77cb0d39c/include/easypr/util/util.h#L17 "Check SAFE_RELEASE once more?") left over?
