### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [liuruoze/EasyPR#64]
I would like to point out that identifiers like "[` __CHARS_RECOGNISE_H__`](https://github.com/liuruoze/EasyPR/blob/7f6ed737a8de98a497e3e62e3763e7e427c937a3/include/easypr/chars_recognise.h#L12)" and "[`__PLATE_DETECT_H__`](https://github.com/liuruoze/EasyPR/blob/3e409cc5ec5a74648191a4d6b4f60befec6f4716/include/easypr/plate_detect.h#L13)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by micooz** [comment]
Yes, the new version will be more standardized.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/liuruoze/EasyPR/commit/32b0560872f789840012bc06ca505ce77cb0d39c#diff-50692f82cf44a629fa9900176b5a3e4aL1 "Deletion of a few underscores").
