### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [liuruoze/EasyPR#65]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidates:
* [CCharsRecognise](https://github.com/liuruoze/EasyPR/blob/7f6ed737a8de98a497e3e62e3763e7e427c937a3/src/core/chars_recognise.cpp#L9 "CCharsRecognise class")
* [CPlateDetect](https://github.com/liuruoze/EasyPR/blob/3e409cc5ec5a74648191a4d6b4f60befec6f4716/src/core/plate_detect.cpp#L9 "CPlateDetect class")

**Comment by micooz** [comment]
Yes, we use singletons in the coming version.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/liuruoze/EasyPR/blob/32b0560872f789840012bc06ca505ce77cb0d39c/src/core/chars_recognise.cpp#L6 "Update candidate: CCharsRecognise class") left over?
