### ISSUE TITLE
Hi 我想问下1.4这个版本什么时候发布

### ISSUE THREAD

**Issue by chenyunbbs** [liuruoze/EasyPR#66]
Hi 我想问下1.4这个版本什么时候发布,或者作者能给我发送一个1.4版本好吗？chenyunNet@163.com
还有ANN模型学习的我训练出来的图片识别很低,能教教我们吗？

**Comment by micooz** [comment]
ANN模型学习可以参考[这里](https://github.com/micooz/EasyPR/blob/master/src/train/ann_train.cpp).
