### ISSUE TITLE
关于easypr/util.h中的getFiles函数

### ISSUE THREAD

**Issue by wrestle** [liuruoze/EasyPR#67]
##认为你们是用的写法在具体上似乎有些结构混乱
- 额我的意思是，有一些看似很浪费的写法。
- 而且对于 32位和64位的需要分别修改代码。
- 我的建议是这样，不如使用微软推荐的写法:

        HANDLE fileHandle;
        WIN32_FIND_DATAA fileData; //这个就无需考虑 32还是64位了

- 使用递归来获取子文件夹内部的文件比用循环来的好多了，尤其是代码的清晰度上，很容易进行重构。
- 如果考虑效率，在一个短小的递归中只要代码足够清晰，编译器能够为你优化出不逊色于循环的执行码来，尤其是对 VC++ 这种怪兽级别的家伙。

        if(fileData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
        {
            if(strcmp(fileData.cFileName, ".") == 0 ||
               strcmp(fileData.cFileName, "..") == 0)
                    continue;
            strcat(tempDirBuf, fileData.cFileName);
            getFile(tempDirBuf, files); // 递归调用，并且使用strcat来代替append让编译器有更好的优化选择。
            ...

- 对于文件

        else
        {
            strcat(tempFileDirBuf, fileData.cFileName);
	    files.pushback(tempFileBuf, files);
        }

- 总体 do...while 使用
    
        do{

                 ....// Something 
        }while(FindNextFile(fileHandle, &fileData) != 0) ;

这是我近来使用你们的项目时候的某些小建议，当然也可能是我考虑的太片面。

**Comment by micooz** [comment]
暂不考虑修改该函数，原因如下：

1. 跨平台的需要，需要同时兼容*nix和Windows
2. 该函数目前在各个平台运行良好
3. 该函数非核心代码
4. 等待各编译器全面支持[C++14](https://isocpp.org/std/status)标准后，采用filesystem标准库实现这部分功能
