### ISSUE TITLE
出現無法啟動程式'C:\EasyPR\\bin\debug\libeasypr.lib'

### ISSUE THREAD

**Issue by zoper** [liuruoze/EasyPR#70]
我的環境是 VS2013 和 OPEN CV 2.4.11 .
編譯後出現這個錯誤,但在C:\EasyPR\bin\debug 下是能找到 libeasypr.lib 的.
怎樣才能解決這個錯誤呢?

**Comment by liuruoze** [comment]
右键选择demo项目，然后选择“设为启动项目”即可

**Comment by zoper** [comment]
THANKS ~
