### ISSUE TITLE
執行完EasyPR.sln沒有生成release,也沒有easypr_test.exe

### ISSUE THREAD

**Issue by steve811127** [liuruoze/EasyPR#73]
![default](https://cloud.githubusercontent.com/assets/14048251/10023260/c4691078-6183-11e5-82ad-c94e6ec761fa.jpg)
執行EasyPR.sln後跳出這個有看到libeasypr.lib但沒easypr_test.exe請問如何解決

**Comment by sef60985** [comment]
把DEMO設定成啟始專案即可。

**Comment by steve811127** [comment]
設定完執行出現fatal error c1083: EasyPR-master\test\main.cpp
是過好多方法一直顯示這個
