### ISSUE TITLE
執行出錯

### ISSUE THREAD

**Issue by sef60985** [liuruoze/EasyPR#74]
我選擇匹量測試之後會跳出這樣的錯誤訊息，麻煩各位前輩給予指教，教後輩如何排除這個錯誤。http://imgur.com/IsqjGly
萬分感激。

**Comment by liuruoze** [comment]
请 @micooz  帮忙看看是什么问题。

**Comment by micooz** [comment]
请贴一下你的配置：

**Demo**

|    配置项   |    值    
|-------------|-----------
| `C/C++`-`附加包含目录` | 
| `链接器`-`附加库目录` | 
| `链接器`-`输入`-`附加依赖项` | 

**EasyPR**

|    配置项   |    值    
|-------------|-----------
| `C/C++`-`附加包含目录` |

**Comment by sef60985** [comment]
已解決，有可能是我之前有用CV寫過相關程式，所以記憶體位置沒有釋放出來。
重灌OS之後就可以正常執行了。
