### ISSUE TITLE
Easy在linux上编译出错

### ISSUE THREAD

**Issue by joewale** [liuruoze/EasyPR#75]
@micooz  您好！我在linux系统Ubuntu14.04上部署您的EasyPR项目，Cmake版本是3.2.3，g++版本是4.8.2，opencv的版本是3.0.0，cmake后，在同一目录下进行make，编译出错，提示文件chars_identify.h中 error:‘CvANN_MLP’ does name a type。相应的文件chars_identify.cpp中的‘ann’没有声明。请问有遇到同样问题的吗，该如何解决？

**Comment by micooz** [comment]
opencv请使用2.4.*版本。
