### ISSUE TITLE
請問如何解決File:f:\dd\vctools\crt\crtw32\misc\dbgheap.c

### ISSUE THREAD

**Issue by steve811127** [liuruoze/EasyPR#78]
執行測試下的任一功能都會出現這個
File:f:\dd\vctools\crt\crtw32\misc\dbgheap.c
![5](https://cloud.githubusercontent.com/assets/14048251/10167785/979769fe-66fc-11e5-8cd1-a1b871a9ec7f.png)

**Comment by micooz** [comment]
请贴一下你的配置：

**Demo**

|    配置项   |    值    
|-------------|-----------
| `C/C++`-`附加包含目录` | 
| `链接器`-`附加库目录` | 
| `链接器`-`输入`-`附加依赖项` | 

**EasyPR**

|    配置项   |    值    
|-------------|-----------
| `C/C++`-`附加包含目录` |

**Comment by steve811127** [comment]
*Demo*
配置项值C/C++-附加包含目录


$(ProjectDir)inc
$(ProjectDir)
D:\CODE\EasyPR-master\test
$(SolutionDir)\include

链接器-附加库目录

D:\opencv\build\x86\vc12\lib

链接器-输入-附加依赖项

opencv_calib3d2411d.lib
opencv_contrib2411d.lib
opencv_core2411d.lib
opencv_features2d2411d.lib
opencv_flann2411d.lib
opencv_gpu2411d.lib
opencv_highgui2411d.lib
opencv_imgproc2411d.lib
opencv_legacy2411d.lib
opencv_ml2411d.lib
opencv_nonfree2411d.lib
opencv_objdetect2411d.lib
opencv_ocl2411d.lib
opencv_photo2411d.lib
opencv_stitching2411d.lib
opencv_superres2411d.lib
opencv_ts2411d.lib
opencv_video2411d.lib
opencv_videostab2411d.lib
opencv_contrib2411d.lib
opencv_core2411d.lib
opencv_features2d2411d.lib
opencv_flann2411d.lib
opencv_gpu2411d.lib
opencv_highgui2411d.lib
opencv_imgproc2411d.lib
opencv_legacy2411d.lib
opencv_ml2411d.lib
opencv_videostab2411d.lib

*EasyPR*
配置项值
C/C++-附加包含目录
$(ProjectDir)\include

2015-09-30 17:11 GMT+08:00 Micooz <notifications@github.com>:

**Comment by steve811127** [comment]
@micooz
@liuruoze

**Comment by Pichairen** [comment]
我也碰到了，请问问题解决了么？？
