### ISSUE TITLE
請問一下 cmake 沒問題但是 make 時遇到這個錯誤 可能是哪邊的問題？謝謝！

### ISSUE THREAD

**Issue by ken1020** [liuruoze/EasyPR#79]
~ $ make
Scanning dependencies of target easypr
[  5%] Building CXX object CMakeFiles/easypr.dir/src/core/core_func.cpp.o
[ 11%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_identify.cpp.o
[ 16%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_recognise.cpp.o
[ 22%] Building CXX object CMakeFiles/easypr.dir/src/core/chars_segment.cpp.o
[ 27%] Building CXX object CMakeFiles/easypr.dir/src/core/feature.cpp.o
[ 33%] Building CXX object CMakeFiles/easypr.dir/src/core/plate.cpp.o
[ 38%] Building CXX object CMakeFiles/easypr.dir/src/core/plate_detect.cpp.o
[ 44%] Building CXX object CMakeFiles/easypr.dir/src/core/plate_judge.cpp.o
[ 50%] Building CXX object CMakeFiles/easypr.dir/src/core/plate_locate.cpp.o
[ 55%] Building CXX object CMakeFiles/easypr.dir/src/core/plate_recognize.cpp.o
[ 61%] Building CXX object CMakeFiles/easypr.dir/src/train/ann_train.cpp.o
[ 66%] Building CXX object CMakeFiles/easypr.dir/src/train/svm_train.cpp.o
[ 72%] Building CXX object CMakeFiles/easypr.dir/src/preprocess/deface.cpp.o
[ 77%] Building CXX object CMakeFiles/easypr.dir/src/preprocess/gdts.cpp.o
[ 83%] Building CXX object CMakeFiles/easypr.dir/src/preprocess/mc_data.cpp.o
[ 88%] Building CXX object CMakeFiles/easypr.dir/src/util/util.cpp.o
[ 94%] Building CXX object CMakeFiles/easypr.dir/src/util/program_options.cpp.o
In file included from /home/pi/EasyPR/src/util/program_options.cpp:1:0:
/home/pi/EasyPR/include/easypr/program_options.h:210:27: sorry, unimplemented: non-static data member initializers
/home/pi/EasyPR/src/util/program_options.cpp: In constructor ‘program_options::Generator::Generator()’:
/home/pi/EasyPR/src/util/program_options.cpp:20:1: error: uninitialized member ‘program_options::Generator::kDelimiter’ with ‘const’ type ‘const char’ [-fpermissive]
CMakeFiles/easypr.dir/build.make:422: recipe for target 'CMakeFiles/easypr.dir/src/util/program_options.cpp.o' failed
make[2]: *** [CMakeFiles/easypr.dir/src/util/program_options.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/easypr.dir/all' failed
make[1]: *** [CMakeFiles/easypr.dir/all] Error 2
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eefolks** [comment]
Ubuntu12.04+ gcc version 4.6.3  ,has the same issue  ,fixed as below locally

commit d3b59c5b58bde6f77bea9eff5272ed03076c702f
Author: shanquan.wang <shanquan.wang@tcl.com>
Date:   Fri Apr 15 16:36:16 2016 +0800

    fixed build error in ubuntu12.04 gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5

diff --git a/include/easypr/util/program_options.h b/include/easypr/util/program_options.h
index 488b620..fb2dd10 100644
--- a/include/easypr/util/program_options.h
+++ b/include/easypr/util/program_options.h
@@ -205,7 +205,7 @@ class Generator {
   bool add_usage_line(const char* option, const char* default_value,
                       const char* description);
 
-  const char kDelimiter = ',';
+  static const char kDelimiter = ',';
   SubroutineCollection subroutines_;
   std::string current_subroutine_;
   Parser* parser_;
