### ISSUE TITLE
关于使用opencv3.0编译遇到的问题

### ISSUE THREAD

**Issue by justinTomas** [liuruoze/EasyPR#84]
环境：vs2013 + opencv3.0
1，在svm_train.cpp中提示CvSVM未声明，3.0版本没有使用CvSVM，与之相关的CvSVMParams，SVM_params也没使用，都会报错。与之似的还有一些，都是因为cv版本变化引起的。
2，标识符“vector”没有加std，不识别，报语法错误
3，还有类似“error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int”错误，感觉是字符引起的，目前还没找到在哪。

**Comment by liuruoze** [comment]
请试试最新的v1.4
