### ISSUE TITLE
字符识别改进（2）

### ISSUE THREAD

**Issue by liuruoze** [liuruoze/EasyPR#9]
目前EasyPR对字符识别的准确率较差，需要改进字符识别。

第二个任务（难度：简单）：
2.在训练数据上训练模型，在测试数据上测试，使用precise与recall和fscore来衡量准确率;

**Comment by ahccom** [comment]
我用cnn进行识别准确率提示很明显。

**Comment by liuruoze** [comment]
nice,   不知道你是否有将代码加入到项目中的计划？
有几个问题想咨询：
有关你用CNN的方式？例如传统的CNN，深度学习的CNN。
使用了哪些库？OpenBLAS？Cafe？boost？
是否使用了GPU？如果使用GPU，是仅在训练时需要使用，还是训练和应用时都需要GPU？

**Comment by liuruoze** [comment]
sorry，回复时没看到你在另外一个帖子里的信息。
tiny-cnn，基于深度学习的cnn识别。intersting......我计划将字符识别的单层神经网络全部替换成cnn，不知道你是否有兴趣实现？

**Comment by liuruoze** [comment]
提交代码的形式以pull request为主，只改变 plate_identify.cpp和h里的内容，其他不动，在整合你的代码之前，我不对那个文件做任何改动。

改动效果：以GDST作为测试集，以平均字符差距的1-2个字符的减少，以及完整匹配率50%的提升为改善目标。

时间1个月左右，OK？

**Comment by liuruoze** [comment]
如果可以做的话，请留下自己的git账号，联系邮箱，qq群名字等信息，我会列入计划进度中。

**Comment by liuruoze** [comment]
此任务已经被1.3版fix，所以close
