### ISSUE TITLE
自带的ann.xml对应的数据集在哪里哇？

### ISSUE THREAD

**Issue by melody-rain** [liuruoze/EasyPR#90]
我用自带的ann.7z训练后的ann.xml的准确率下降很多啊... @liuruoze

**Comment by liuruoze** [comment]
应该不会的，我用后的准确率基本上没太大变化。可否贴出你的准确率结果图？

**Comment by melody-rain** [comment]
总车牌图片数:204张,  未识别车牌图片:0张,  定位率:100%  
平均字符差距:0.622549个,  完全匹配数:158张,  完全匹配率:77.451%  

vs

总车牌图片数:204张,  未识别车牌图片:0张,  定位率:100%  
平均字符差距:0个,  完全匹配数:204张,  完全匹配率:100%  

我有204张完全识别出来的图，然后用你的数据库，重新train了一个ann.xml，正确率就只有77%了。

或者说，我train的ann.xml和自带的ann.xml会有很大差距。是和计算精度，图片的顺序之类的都有关系吗？

你提供的ann.xml就是用你提供的数据库train出来的？

**Comment by liuruoze** [comment]
解答最后一个问题：是的。
至今为止，在我们测试的过程中，都没有完全匹配率达到100%的情况，定位率更是不可能达到100%。
下面是我最新的一次测试结果：
2016-01-13 16:59:04
总图片数:204张,  未识出图片:5张,  定位率:97.549%  
平均字符差距:0.688442个,  完全匹配数:141张,  完全匹配率:70.8543%  
总时间:173秒,  平均执行时间:0.848039秒

如果达到了你所说的那个结果的话，我只能说，肯定是哪边出了问题。
