### ISSUE TITLE
一些问题求解答

### ISSUE THREAD

**Issue by SawyerSun** [liuruoze/EasyPR#92]
一.前几天下了代码编译后运行发现两个问题
1. 测试选项中任何一项都会报错，openCV Error: Assertion failed (scn == 3 || scn == 4)  && (depth == CV_8U) && (CV_32F)。
2. 批量测试显示找不到文件
二. 今天下载了最新打代码，编译后运行demo.exe只有一行，没有选项
另外，我的环境是64位win10 使用opencv3.1 编译的目标平台是64位

**Comment by micooz** [comment]
你demo.exe的执行路径是?

**Comment by SawyerSun** [comment]
是我执行路径不对，没有拷贝到根目录。谢谢。
