### ISSUE TITLE
about ver1.4 ann.xml 

### ISSUE THREAD

**Issue by daiyinger** [liuruoze/EasyPR#94]
使用自己从resources/train/ann.7z的解压后资源训练生成的ann.xml替换当前的1.4版本的ann.xml感觉效果明显差很多，请问作者训练ann.xml从哪些方面进行了优化呢？

**Comment by liuruoze** [comment]
我们将会检查这个问题，有可能是因为更新了旧的文件所导致的。

**Comment by liuruoze** [comment]
@daiyinger ， 你好，经过测试，发现用resource的data训练后的完整识别率并没有下降。
原始的ann.xml效果：
2016-01-29 07:55:43
总图片数:204,  未识出图片:5,  定位率:97.549%  
平均字符差距:0.643216,  完全匹配数:144,  完全匹配率:72.3618%  
总时间:209秒,  平均执行时间:1.02451秒

替换新的ann.xml的效果：
2016-01-29 08:16:04
总图片数:204,  未识出图片:5,  定位率:97.549%  
平均字符差距:0.643216,  完全匹配数:144,  完全匹配率:72.3618%  
总时间:210秒,  平均执行时间:1.02941秒

如果还有问题的话，可以反馈。这个issue在一周后看情况会被关闭。

**Comment by daiyinger** [comment]
你好！不好意思，后面发现自己训练样本测试结果不好的原因是定位率明显下降了，ann.xml训练后大小为220KB,使用原始的svm.xml，对比如下
2016-01-29 09:08:46

总图片数:204,  未识出图片:5,  定位率:97.549%  

平均字符差距:0.633166,  完全匹配数:144,  完全匹配率:72.3618%  

总时间:112秒,  平均执行时间:0.54902秒

2016-01-29 09:16:55

总图片数:204,  未识出图片:5,  定位率:97.549%  

平均字符差距:0.653266,  完全匹配数:141,  完全匹配率:70.8543%  

总时间:111秒,  平均执行时间:0.544118秒
但是如果使用自己按svm_train.c中的参数以及样本训练得到的svm.xml定位率明显下降
总图片数:204,  未识出图片:97,  定位率:52.451%  

平均字符差距:2.99065,  完全匹配数:37,  完全匹配率:34.5794%  

总时间:139秒,  平均执行时间:0.681373秒

2016-01-26 18:05:31
应该是svm训练这儿出了问题 ，参数训练不熟悉，还在补功课....

**Comment by liuruoze** [comment]
1.4版的SVM是有问题的，不要用其训练新的SVM模型。这个原因是由于opencv3.0版本之后的SVM的bug所导致的。

如果想训练SVM模型，可以使用1.3分支来训练。训练好的模型可以被1.4版使用。
