### ISSUE TITLE
按照使用方法执行遇到问题

### ISSUE THREAD

**Issue by shawChiang** [liuruoze/EasyPR#95]
执行$ ./build 时 显示
 ./build : no such file or directory
请问如何解决??  thanks!

**Comment by micooz** [comment]
请先看看下面这条命令的结果：

    $ ls | grep build.sh

如果输出`build.sh`, 再执行：

    $ chmod +x build.sh
    $ ./build.sh

如果没有输出请`cd`到项目目录重复上面的操作即可。

**Comment by shawChiang** [comment]
谢谢 @micooz   已经解决了,谢谢谢谢谢谢
