### ISSUE TITLE
源文件中demo项目可以运行，但是libeasypr却不能启动（见截图）

### ISSUE THREAD

**Issue by heatMa** [liuruoze/EasyPR#98]
![image](https://cloud.githubusercontent.com/assets/18495380/14579414/e16443b0-03da-11e6-835e-9cfdf0cc3d5e.png)
![default](https://cloud.githubusercontent.com/assets/18495380/14579419/110d582c-03db-11e6-980b-7e5517883ffb.png)
我刚学习opencv，毕业设计要做这个，我的opencv配置都没问题，请问下这时什么情况？还望赐教啊，谢谢啦！

**Comment by liuruoze** [comment]
请右键点击Demo工程，选择“设为启动项目”，再重新运行即可。

**Comment by liuruoze** [comment]
如果只是运行lib的话，lib本来就无法单独运行，必须附在某个exe上才能运行，可以百度相关的问题。
