### ISSUE TITLE
EasyPR配置问题

### ISSUE THREAD

**Issue by cxingxing** [liuruoze/EasyPR#99]
在release下运行正常，但是在debug下运行会报错 error C2039: “ANN_MLP”: 不是“cv”的成员  e:\licenseplate\easypr-master\include\easypr\train\ann_train.h。 
我opencv是用的3.0，配置完成后，测试程序都可以正常运行。请教大神解答！

**Comment by lbyfind** [comment]
同样的问题，请各位大神解答

**Comment by liuruoze** [comment]
检查一下debug模式引用的库吧
